import type { Drill } from '../types'

// Coordenadas de media cancha para los patrones: x va de -5,5 (línea de dobles
// izquierda) a 5,5, z va de 0 (línea de fondo) a 11,9 (red). Las líneas de
// individuales están en x = ±4,1, la línea de saque en z = 5,5 y la T en [0, 5.5].

export const DRILLS: Drill[] = [
  // ------------------------------------------------------------ juego de pies
  {
    id: 'ready-position-and-split-step',
    name: 'Posición de espera y split step',
    section: 'footwork',
    level: 'beginner',
    goal: 'Automatizar el pequeño salto que te pone en marcha temprano, para que tu primer paso hacia cada pelota sea rápido y equilibrado.',
    equipment: 'Dos conos o tubos de pelotas, un compañero o entrenador que pueda indicar direcciones',
    setup: 'Párate sobre la marca central a medio metro detrás de la línea de fondo. Coloca un cono a un metro a cada lado.',
    steps: [
      'Adopta la posición de espera: pies algo más abiertos que los hombros, rodillas relajadas, peso en la punta de los pies, cabeza de la raqueta arriba y al frente.',
      'Tu compañero imita un swing. Cuando su brazo va hacia adelante, salta unos centímetros del suelo y aterriza con los pies un poco más abiertos que antes.',
      'Aterriza en el momento en que él haría contacto y luego impúlsate con el pie exterior hacia el cono que tu compañero señala.',
      'Da un primer paso grande, simula un golpe en el cono y vuelve a la marca central con pasos laterales.',
      'Vuelve a la posición de espera y aguarda la siguiente señal. No saltes hasta ver que empieza el swing.',
      'Tras diez repeticiones, pide a tu compañero que añada amagues para que aprendas a aguantar el salto hasta la señal real.',
    ],
    reps: '3 series de 10 splits, 30 segundos de descanso entre series',
    coachingCues: [
      'Salto pequeño, aterrizaje ancho. Estás descargando peso, no saltando.',
      'Aterriza sobre la punta de ambos pies con las rodillas flexionadas, nunca sobre los talones.',
      'Sincroniza el aterrizaje con el contacto del rival, no con el bote.',
      'Impúlsate con el pie más alejado de la pelota. Tu primer paso debe ser explosivo.',
    ],
    pattern: {
      points: [
        [0, 0.5],
        [-1, 0.5],
        [0, 0.5],
        [1, 0.5],
        [0, 0.5],
      ],
      cones: [
        [-1, 0.5],
        [1, 0.5],
      ],
    },
    studio: 'split-step',
  },
  {
    id: 'side-shuffle-recovery',
    name: 'Recuperación con pasos laterales',
    section: 'footwork',
    level: 'beginner',
    goal: 'Aprender a recuperar hacia el centro mirando a la red, para poder cambiar de dirección en el instante en que se golpea la siguiente pelota.',
    equipment: 'Tres conos',
    setup: 'Coloca un cono en la marca central y uno a 3,5 metros a cada lado, todos a un metro detrás de la línea de fondo.',
    steps: [
      'Empieza en el cono central en posición de espera, con el pecho hacia la red.',
      'Desplázate con pasos laterales hasta el cono izquierdo. Guía con el pie izquierdo y nunca dejes que los pies se crucen o se junten.',
      'Toca el cono con la raqueta, simula un revés y vuelve al centro con pasos laterales.',
      'Haz un pequeño split step en el centro, luego desplázate al cono derecho y simula una derecha.',
      'Vuelve al centro con pasos laterales y haz otro split. Eso es un viaje completo.',
      'Mantén las caderas bajas todo el tiempo. Si subes y bajas, estás perdiendo tiempo.',
    ],
    reps: '6 viajes completos, 45 segundos de descanso, repetir 3 veces',
    coachingCues: [
      'Bajo y ancho. Imagina que te deslizas bajo una barra a la altura del hombro.',
      'Los pies nunca se cruzan. Empuja con la pierna de atrás, alcanza con la de adelante.',
      'Los ojos siguen al rival imaginario, no a los conos.',
      'Termina cada recuperación con un split step, no con una frenada en seco.',
    ],
    pattern: {
      points: [
        [0, 0.8],
        [-3.5, 0.8],
        [0, 0.8],
        [3.5, 0.8],
        [0, 0.8],
      ],
      cones: [
        [-3.5, 0.8],
        [0, 0.8],
        [3.5, 0.8],
      ],
    },
    studio: 'shuffle',
  },
  {
    id: 'crossover-step',
    name: 'Paso cruzado',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Cubrir pelotas abiertas rápido con un paso cruzado y usar el mismo paso para recuperar cuando el camino de vuelta al centro es largo.',
    equipment: 'Dos conos',
    setup: 'Conos en cada línea lateral de individuales, un metro detrás de la línea de fondo. Empieza en la marca central en posición de espera.',
    steps: [
      'Split step, luego gira las caderas y cruza el pie derecho por delante del izquierdo para correr hacia el cono izquierdo.',
      'Da dos o tres zancadas, planta el pie exterior junto al cono y simula un revés abierto.',
      'Recupera con un paso cruzado: impúlsate con la pierna exterior, lleva la pierna lejana por delante del cuerpo y termina los últimos dos metros con pasos laterales.',
      'Split en el centro y repite hacia el cono derecho con una derecha abierta.',
      'Cuando tengas el ritmo, pide a un compañero que señale izquierda o derecha al azar.',
      'Añade una pelota: el compañero lanza con la mano a lo ancho y tú golpeas desde la pierna exterior antes de recuperar.',
    ],
    reps: '8 pelotas abiertas por lado, 2 series, 60 segundos de descanso entre series',
    coachingCues: [
      'Paso cruzado para la distancia, pasos laterales para los últimos pasos. No hagas cinco metros de pasos laterales.',
      'Gira primero las caderas, los pies siguen.',
      'Planta fuerte el pie exterior para poder empujar directo hacia el centro.',
      'Mantén la cabeza de la raqueta arriba durante la carrera; la necesitas lista al final.',
    ],
    pattern: {
      points: [
        [0, 0.8],
        [-4.5, 0.8],
        [0, 0.8],
        [4.5, 0.8],
        [0, 0.8],
      ],
      cones: [
        [-4.5, 0.8],
        [4.5, 0.8],
      ],
    },
    studio: 'crossover',
  },
  {
    id: 'spider-drill',
    name: 'Ejercicio de la araña',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Construir la velocidad multidireccional y la fuerza de frenado que el tenis realmente exige, y obtener un tiempo repetible contra el que medirte.',
    equipment: 'Cinco pelotas de tenis, una raqueta apoyada en la marca central, un cronómetro',
    setup: 'Coloca una pelota en cada uno de cinco puntos: las dos esquinas entre línea de fondo y línea de individuales, las dos esquinas donde las líneas de individuales tocan la línea de saque, y la T de saque. Deja tu raqueta plana en la marca central como base.',
    steps: [
      'Empieza en la marca central en posición de espera. Tu compañero arranca el cronómetro con tu primer movimiento.',
      'Esprinta a la esquina izquierda de la línea de fondo, recoge la pelota, vuelve corriendo y colócala sobre la raqueta.',
      'Corre a la esquina izquierda de la línea de saque, recoge la pelota y tráela a la base.',
      'Corre a la T de saque y vuelve, luego a la esquina derecha de la línea de saque y vuelve.',
      'Termina con la esquina derecha de la línea de fondo. El cronómetro se detiene cuando la quinta pelota cae sobre la raqueta.',
      'Descansa por completo y luego invierte el orden para empezar por la derecha.',
      'Anota cada tiempo. Los buenos jugadores de club lo hacen en unos 17 a 20 segundos; los juniors fuertes y jugadores universitarios, por debajo de 16.',
    ],
    reps: '4 a 6 recorridos cronometrados con 90 segundos de descanso entre ellos',
    coachingCues: [
      'Frena con pasos cortos y la cadera baja; no te estrelles contra una pierna recta.',
      'Flexiona las rodillas para recoger la pelota, no solo la espalda.',
      'Mira a la red en las distancias laterales cortas; gira y corre en las largas.',
      'Colocar la pelota, no lanzarla, es parte de la prueba. Control bajo fatiga.',
    ],
    pattern: {
      points: [
        [0, 0],
        [-4.1, 0],
        [0, 0],
        [-4.1, 5.5],
        [0, 0],
        [0, 5.5],
        [0, 0],
        [4.1, 5.5],
        [0, 0],
        [4.1, 0],
        [0, 0],
      ],
      cones: [
        [-4.1, 0],
        [-4.1, 5.5],
        [0, 5.5],
        [4.1, 5.5],
        [4.1, 0],
      ],
    },
  },
  {
    id: 'figure-eight-baseline',
    name: 'Ocho en la línea de fondo',
    section: 'footwork',
    level: 'beginner',
    goal: 'Practicar el cambio de dirección continuo manteniendo el cuerpo de frente a la red, como haces durante un peloteo largo desde el fondo.',
    equipment: 'Dos conos',
    setup: 'Conos a 2,5 metros a cada lado de la marca central, a un metro y medio detrás de la línea de fondo.',
    steps: [
      'Empieza entre los conos mirando a la red.',
      'Desplázate a la izquierda con pasos laterales y rodea el cono izquierdo: por delante, por fuera y por detrás.',
      'Cruza el medio y rodea el cono derecho en sentido contrario, de modo que tu recorrido dibuje un ocho.',
      'Mantente de frente a la red todo el tiempo. Usa pasos laterales en los lados y pasos cortos de ajuste en las curvas.',
      'Añade una derecha simulada cada vez que pases el cono derecho y un revés simulado en el cono izquierdo.',
      'Tras 30 segundos, cambia a una versión en la que corras hacia adelante y hacia atrás alrededor de los conos.',
    ],
    reps: '30 segundos de trabajo, 30 de descanso, 6 rondas',
    coachingCues: [
      'Pasos cortos alrededor del cono, pasos grandes entre ellos.',
      'Cabeza nivelada, sin rebotar. Tus ojos deben mantenerse estables como si siguieras una pelota.',
      'Guía con la cadera, no con el hombro, al cambiar de dirección.',
    ],
    pattern: {
      points: [
        [0, 1.5],
        [-2.5, 2.5],
        [-3.5, 1.5],
        [-2.5, 0.5],
        [0, 1.5],
        [2.5, 2.5],
        [3.5, 1.5],
        [2.5, 0.5],
      ],
      loop: true,
      cones: [
        [-2.5, 1.5],
        [2.5, 1.5],
      ],
    },
  },
  {
    id: 'alley-hops',
    name: 'Saltos en el pasillo',
    section: 'footwork',
    level: 'beginner',
    goal: 'Desarrollar pies rápidos y ligeros y rigidez de tobillo para poder ajustar la posición con saltitos diminutos antes del contacto.',
    equipment: 'Nada, solo el pasillo de dobles',
    setup: 'Párate en el pasillo de dobles junto a la línea de fondo, mirando a la red, con ambos pies justo por fuera de la línea lateral de individuales.',
    steps: [
      'Salta de lado sobre la línea de individuales con los pies juntos, aterriza suave y salta de vuelta.',
      'Sigue saltando a través del pasillo durante 20 segundos, avanzando muy ligeramente con cada salto.',
      'Cambia a saltos a una pierna: solo pie izquierdo durante 15 segundos, luego solo pie derecho.',
      'En la siguiente ronda, salta sobre la línea y toca el suelo con la cabeza de la raqueta después de cada aterrizaje.',
      'Termina con pies rápidos: pasos diminutos alternos sobre la línea lo más rápido posible durante 15 segundos.',
    ],
    reps: '4 rondas de la secuencia completa con 40 segundos de descanso',
    coachingCues: [
      'Aterriza en silencio. Pies ruidosos significan aterrizajes rígidos.',
      'Quédate en la punta de los pies con los talones apenas rozando el suelo.',
      'Brazos relajados y raqueta al frente, como si una pelota pudiera llegar en cualquier momento.',
    ],
    pattern: {
      points: [
        [4.1, 0.5],
        [5.5, 1],
        [4.1, 1.5],
        [5.5, 2],
        [4.1, 2.5],
        [5.5, 3],
      ],
      cones: [
        [4.1, 0.5],
        [5.5, 3],
      ],
    },
  },
  {
    id: 'serve-plus-one-recovery',
    name: 'Saque más uno y recuperación',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Aterrizar del saque equilibrado e inmediatamente listo para la devolución, luego pegar un primer golpe de fondo sólido y recuperar.',
    equipment: 'Canasto de pelotas, un cono, un compañero que lance',
    setup: 'Saca desde el lado de iguales, a un metro a la derecha de la marca central. Coloca un cono a tres metros a la derecha de la marca central, un metro detrás de la línea de fondo, donde cae una devolución típica.',
    steps: [
      'Saca al cuadro de iguales. Aterriza sobre el pie delantero dentro de la línea de fondo, con la pierna trasera pateando hacia atrás para equilibrar.',
      'Da un paso de recuperación hacia atrás de la línea de fondo y haz el split step cuando el receptor haría contacto.',
      'Tu compañero lanza con la mano o con la raqueta una pelota hacia el cono en el momento en que aterrizas.',
      'Muévete hacia la pelota con un paso cruzado, colócate en posición semiabierta y pega una derecha cruzada.',
      'Recupera con pasos laterales hasta justo a la derecha de la marca central y vuelve a hacer el split.',
      'Alterna: cada segundo saque, el compañero lanza al revés en su lugar.',
    ],
    reps: '10 secuencias de saque más uno, 3 series, 90 segundos de descanso entre series',
    coachingCues: [
      'El equilibrio al aterrizar es todo el sentido de la terminación del saque. Clávalo.',
      'Split antes de la devolución, no después. Mira la raqueta del receptor.',
      'Pega el más uno con fuerza a un blanco grande. No apuntes a las líneas con la primera pelota.',
      'Recupera hacia el lado al que golpeaste, no exactamente al centro.',
    ],
    pattern: {
      points: [
        [1, 0],
        [0.8, 0.6],
        [0.8, 0.8],
        [3, 1],
        [0.5, 0.8],
      ],
      cones: [
        [3, 1],
      ],
    },
  },
  {
    id: 'approach-and-split',
    name: 'Subida y split',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Avanzar a través de un golpe de subida sin detenerte, y hacer el split step antes de la volea para que nunca te sorprendan a media zancada en la red.',
    equipment: 'Canasto de pelotas, dos conos, un lanzador',
    setup: 'Un cono cerca de la línea de saque, justo a la derecha del centro, donde cae la pelota corta; otro dos metros dentro de la línea de saque, desde donde quieres volear. Empieza en la marca central.',
    steps: [
      'El lanzador juega una pelota corta al primer cono. Corre hacia adelante y pega una subida cortada o plana paralela con paso carioca o en carrera.',
      'No te detengas tras el contacto. Sigue avanzando en línea recta hacia el segundo cono.',
      'El lanzador inicia el siguiente swing cuando llegas al cono. Split step y aterriza ancho.',
      'Muévete en diagonal hacia la volea, golpéala seca y da un pequeño paso más hacia adelante.',
      'Vuelve con pasos laterales al centro de los cuadros de saque y termina en posición de espera.',
      'Repite subiendo por el lado del revés, luego mézclalos al azar.',
    ],
    reps: '8 secuencias por lado, 2 series, 60 segundos de descanso entre series',
    coachingCues: [
      'Sube y sigue avanzando. El golpe es parte de la carrera, no una parada.',
      'Split cuando la raqueta del rival se mueva, estés donde estés en la cancha.',
      'Aterriza el split con el peso adelante para poder atacar la volea.',
      'Sigue la dirección de tu subida: paralela significa desplazarte hacia ese lado.',
    ],
    pattern: {
      points: [
        [0, 0.5],
        [1.5, 4],
        [1, 8],
        [0.5, 9.5],
        [0, 7],
      ],
      cones: [
        [1.5, 4],
        [1, 8],
      ],
    },
  },
  {
    id: 'drop-step-for-the-lob',
    name: 'Paso atrás para el globo',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Girar y cubrir un globo con un paso atrás y pasos cruzados en lugar de retroceder de espaldas, para llegar al remate equilibrado y detrás de la pelota.',
    equipment: 'Canasto de pelotas, un cono, un lanzador que pueda tirar globos',
    setup: 'Empieza a unos tres metros de la red, ligeramente a la derecha del centro, en posición de espera de volea. Coloca un cono cerca de la línea de saque, donde botaría un globo decente.',
    steps: [
      'El lanzador tira un globo por encima de tu hombro derecho.',
      'Paso atrás: retrocede de inmediato con el pie derecho y gira los hombros de lado, señalando la pelota con la mano no dominante.',
      'Usa pasos cruzados para retroceder hasta debajo de la pelota. Nunca corras hacia atrás mirando a la red.',
      'Colócate con el peso en el pie de atrás, luego simula un remate mientras te impulsas hacia arriba y adelante.',
      'Aterriza y vuelve directo a la posición de red con pasos laterales.',
      'Progresa a pegar remates reales y luego a globos sobre el hombro izquierdo, donde girarás hacia el otro lado.',
    ],
    reps: '10 globos por hombro, 2 series, 60 segundos de descanso entre series',
    coachingCues: [
      'Primero el paso atrás. El paso y el giro ocurren juntos.',
      'Señala la pelota para mantener los hombros de lado y el ojo que sigue la pelota estable.',
      'Colócate detrás de la pelota, no debajo. Quieres avanzar hacia el contacto.',
      'Si el globo es demasiado profundo, déjalo botar y pega un smash tras el bote.',
    ],
    pattern: {
      points: [
        [0.5, 9],
        [1, 7.5],
        [1.5, 6],
        [2, 4.5],
        [0.5, 9],
      ],
      cones: [
        [2, 4.5],
      ],
    },
  },
  {
    id: 'mirror-drill-with-partner',
    name: 'Ejercicio del espejo con compañero',
    section: 'footwork',
    level: 'beginner',
    goal: 'Reaccionar a una señal impredecible y moverte en todas las direcciones con el juego de pies correcto, en un juego que nunca aburre.',
    equipment: 'Cuatro conos, un compañero',
    setup: 'Marca un rectángulo de cinco metros de ancho y unos dos metros y medio de fondo detrás de la línea de fondo. Los compañeros se ubican frente a frente a través de la red o uno junto al otro; uno es el líder.',
    steps: [
      'Ambos empiezan en posición de espera. El líder se mueve a cualquier punto del rectángulo con pasos laterales, cruzados y cortos.',
      'El seguidor imita cada movimiento lo más fielmente posible, manteniéndose de frente al líder.',
      'El líder cambia de dirección al menos cada dos segundos, mezclando movimientos laterales, hacia adelante y hacia atrás.',
      'Tras 20 segundos, congelen. Observen cuánto se han separado y cambien de rol.',
      'Tercera ronda: el líder añade golpes simulados y el seguidor debe copiar el golpe además del movimiento.',
      'Cuarta ronda: el líder intenta despistar al seguidor con amagues, poniendo a prueba su split step.',
    ],
    reps: '20 segundos de trabajo, 20 de descanso, 8 rondas alternando el líder',
    coachingCues: [
      'Seguidor: mira las caderas, no los pies. Las caderas te dicen hacia dónde va alguien.',
      'Mantente bajo entre movimientos. Erguirse entre movimientos es lo que te hace llegar tarde.',
      'Líder: sé honesto y usa juego de pies real de tenis, no pasos de baile.',
    ],
    pattern: {
      points: [
        [0, 1],
        [-2, 1],
        [-1, 2.5],
        [1.5, 2],
        [2, 0.5],
        [0, 1],
      ],
      cones: [
        [-2.5, 0.5],
        [2.5, 0.5],
        [-2.5, 3],
        [2.5, 3],
      ],
    },
  },
  {
    id: 'cone-triangle-hitting',
    name: 'Triángulo de conos con golpes',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Combinar el movimiento hacia una derecha abierta, un revés abierto y una pelota corta con una recuperación completa entre cada uno, exactamente como en un punto real.',
    equipment: 'Tres conos, canasto de pelotas, un lanzador',
    setup: 'Conos a tres metros a izquierda y derecha de la marca central sobre la línea de fondo, y un cono en el medio a unos tres metros dentro de la línea de fondo. Empieza en la marca central.',
    steps: [
      'El lanzador juega una pelota al cono izquierdo. Muévete con pasos cruzados, pega un revés cruzado y vuelve al centro con pasos laterales.',
      'Split step. El siguiente lanzamiento va al cono derecho: derecha cruzada, recupera.',
      'Split. El tercer lanzamiento es corto al cono del medio. Avanza, pega una derecha paralela y retrocede hasta la línea de fondo.',
      'Ese triángulo es una repetición. El lanzador debe lanzar cuando llegas al centro, no antes.',
      'Cada tercer triángulo, invierte el orden para que no empieces a adivinar.',
      'Para una versión avanzada, el lanzador dice a qué cono va un instante antes de lanzar.',
    ],
    reps: '6 triángulos por serie, 3 series, 90 segundos de descanso entre series',
    coachingCues: [
      'Recupera antes de que lancen la siguiente pelota. Si aún te estás moviendo, llegas tarde.',
      'Golpea desde la pierna exterior en las pelotas abiertas y luego empuja de vuelta con esa misma pierna.',
      'En la pelota corta, muévete a través de ella. No corras, frenes y luego hagas el swing.',
      'Mantén la misma forma de swing cuando estés cansado. Los ejercicios de juego de pies tratan de golpear bien en movimiento, no solo de moverse.',
    ],
    pattern: {
      points: [
        [0, 0.8],
        [-3, 1],
        [0, 0.8],
        [3, 1],
        [0, 0.8],
        [0, 3],
        [0, 0.8],
      ],
      cones: [
        [-3, 1],
        [3, 1],
        [0, 3],
      ],
    },
  },

  // ------------------------------------------------------------- coordinación
  {
    id: 'ball-bounce-and-catch',
    name: 'Bote y atrapa',
    section: 'coordination',
    level: 'beginner',
    goal: 'Enseñar a los jugadores jóvenes a seguir una pelota que bota y a juzgar dónde estará, antes de que intervenga la raqueta.',
    equipment: 'Una pelota roja o naranja de baja compresión por niño, tiza o un marcador plano',
    setup: 'Cada niño en su propio espacio con una pelota, sobre una superficie lisa donde la pelota bote fiel.',
    steps: [
      'Deja caer la pelota desde la cintura y atrápala con ambas manos tras un bote. Diez veces.',
      'Suelta y atrapa con una sola mano, luego con la otra.',
      'Bota la pelota contra el suelo con una mano y atrápala tras el bote con la misma mano. Diez seguidas.',
      'Lanza la pelota hacia arriba con suavidad, deja que bote una vez y atrápala. Mueve los pies para que bote delante de ti.',
      'Versión en parejas: uno lanza una pelota lenta por debajo, el otro la deja botar una vez y la atrapa, luego la devuelve rodando.',
      'Juego: ¿cuántos bote-y-atrapa puedes hacer caminando hasta la red y de vuelta?',
    ],
    reps: '10 de cada variante, luego 5 minutos de juegos',
    coachingCues: [
      'Mira la pelota hasta que llegue a tus manos.',
      'Mueve los pies para que la pelota venga a ti; no estires el brazo.',
      'Atrapa con manos suaves, como si atraparas un huevo.',
    ],
  },
  {
    id: 'racquet-balance-walk',
    name: 'Caminata con la pelota en equilibrio',
    section: 'coordination',
    level: 'beginner',
    goal: 'Acostumbrarse a sentir la cabeza de la raqueta y controlarla con pequeños ajustes, para que la raqueta se convierta en una extensión de la mano.',
    equipment: 'Una raqueta junior y una pelota por niño, unos cuantos conos',
    setup: 'Arma un recorrido sencillo con conos desde la línea de fondo hasta la línea de saque.',
    steps: [
      'Sostén la raqueta al frente con la cara plana, como una bandeja, y equilibra la pelota sobre las cuerdas.',
      'Camina despacio de la línea de fondo a la línea de saque sin que la pelota caiga. Vuelve a empezar si se cae.',
      'Vuelve zigzagueando entre los conos.',
      'Siguiente ronda: da vuelta la raqueta para equilibrar la pelota sobre la otra cara de las cuerdas, luego cambia de mano.',
      'Intenta caminar con la cara de la raqueta extendida al costado, como preparándote para pegar una derecha.',
      'Carrera de relevos: equipos de dos o tres, pasen la pelota de raqueta a raqueta sin usar las manos.',
    ],
    reps: '3 recorridos por variante, luego un relevo de 5 minutos',
    coachingCues: [
      'Empuñadura suave. Apretar fuerte hace temblar la raqueta.',
      'Mira la pelota, no tus pies. Tus pies se las arreglarán.',
      'Ajustes diminutos; mantén la cara de la raqueta paralela al suelo.',
    ],
  },
  {
    id: 'self-rally-ups-and-downs',
    name: 'Peloteo individual: arriba y abajo',
    section: 'coordination',
    level: 'beginner',
    goal: 'Aprender a hacer que el centro de las cuerdas encuentre la pelota una y otra vez, con la raqueta haciendo el trabajo y los ojos guiando.',
    equipment: 'Una raqueta y una pelota roja o naranja por niño',
    setup: 'Cada niño en su propio espacio, a al menos dos metros de cualquier otro.',
    steps: [
      'Abajo: bota la pelota contra el suelo con la raqueta, como driblando en básquet. Cuenta cuántas seguidas.',
      'Arriba: golpea la pelota hacia arriba con las cuerdas, a la altura de la cabeza, y atrápala. Luego intenta dos arriba, luego tres.',
      'Sigue con tantos arriba como puedas. Flexiona las rodillas y mantente debajo de la pelota.',
      'Alterna un arriba, luego gira la raqueta y golpea el siguiente con la otra cara.',
      'Combina: un arriba, déjala botar, un abajo, de vuelta a un arriba.',
      'Desafío: arriba mientras caminas, luego arriba mientras te sientas y te levantas.',
    ],
    reps: '2 minutos de cada uno, intenta superar tu mejor racha',
    coachingCues: [
      'Mira cómo la pelota toca las cuerdas cada vez.',
      'Toques pequeños. Los swings grandes hacen que la pelota se descontrole.',
      'Mueve los pies para quedar debajo de la pelota en lugar de estirarte hacia ella.',
      'Cara de la raqueta plana hacia el cielo para los arriba, hacia el suelo para los abajo.',
    ],
  },
  {
    id: 'toss-and-clap',
    name: 'Lanza y aplaude',
    section: 'coordination',
    level: 'beginner',
    goal: 'Mejorar el seguimiento de la pelota, el timing y el ritmo, y construir el control del lanzamiento que el saque necesitará más adelante.',
    equipment: 'Una pelota por niño',
    setup: 'Cada niño de pie con espacio alrededor, pies separados al ancho de los hombros.',
    steps: [
      'Lanza la pelota recta hacia arriba hasta justo por encima de la cabeza y atrápala con la misma mano. Diez veces, sin perseguirla.',
      'Lanza, aplaude una vez mientras la pelota está en el aire, atrapa.',
      'Lanza, aplaude dos veces, atrapa. Luego tres aplausos si puedes.',
      'Lanza, gira las caderas de lado y atrapa con la palma hacia el cielo, como en un lanzamiento de saque.',
      'Lanza con la mano no dominante y atrapa con la dominante.',
      'Versión en parejas: lanza para ti mismo, aplaude, y tu compañero cuenta cuántas atrapadas limpias seguidas.',
    ],
    reps: '10 de cada variante',
    coachingCues: [
      'Eleva la pelota desde la palma y los dedos, no con un latigazo de muñeca.',
      'Lanza al mismo punto cada vez para que nunca tengas que mover los pies.',
      'Ojos en la pelota en lo más alto del lanzamiento; ahí es cuando es más fácil verla.',
    ],
  },
  {
    id: 'two-ball-juggle-drop',
    name: 'Malabar y caída con dos pelotas',
    section: 'coordination',
    level: 'beginner',
    goal: 'Desafiar la visión periférica, el timing y la independencia de las dos manos con un juego que se siente como malabares pero sigue siendo alcanzable.',
    equipment: 'Dos pelotas por niño, de colores distintos si es posible',
    setup: 'Cada niño con una pelota en cada mano, de pie y quieto.',
    steps: [
      'Lanza hacia arriba la pelota de la mano derecha, pasa rápido la pelota de la izquierda a la derecha y atrapa la que cae con la izquierda. Despacio.',
      'Repite empezando con la mano izquierda.',
      'Caída de dos pelotas: sostén ambas a la altura del hombro, suéltalas al mismo tiempo y atrapa las dos tras un bote.',
      'Suelta ambas, aplaude y atrapa las dos tras el bote.',
      'Suelta ambas y atrápalas cruzadas: la mano derecha atrapa la pelota izquierda y viceversa.',
      'Tu compañero te lanza dos pelotas a la vez, una con bote bajo y otra alto. Atrapa las dos.',
    ],
    reps: '10 intentos por variante, cuenta los aciertos',
    coachingCues: [
      'Mira entre las dos pelotas, no a una de ellas.',
      'Lanza bajo. Un lanzamiento a la altura de los ojos es suficiente.',
      'Relaja las manos y deja que la pelota caiga en ellas.',
    ],
  },
  {
    id: 'reaction-ball-drop',
    name: 'Caída de pelota de reacción',
    section: 'coordination',
    level: 'beginner',
    goal: 'Afinar el tiempo de reacción y el primer paso explosivo, las dos cosas que separan alcanzar una pelota de verla pasar.',
    equipment: 'Una pelota, un compañero, opcionalmente una pelota de reacción de seis lados',
    setup: 'Tu compañero se ubica dos metros frente a ti sosteniendo una pelota a la altura del hombro. Tú estás en posición de espera.',
    steps: [
      'Tu compañero suelta la pelota sin aviso. Esprinta hacia adelante y atrápala tras un bote, antes del segundo.',
      'Vuelve al inicio. Tu compañero la suelta otra vez, ahora desde más bajo, para que tengas menos tiempo.',
      'Tu compañero sostiene una pelota en cada mano y suelta una al azar. Reacciona hacia el lado correcto.',
      'Empiezas de espaldas. Tu compañero dice «ya» al soltarla; gira y atrapa tras un bote.',
      'Tu compañero suelta la pelota dos metros a tu izquierda o derecha para que primero tengas que moverte lateralmente.',
      'Reemplaza la pelota de tenis por una pelota de reacción para un bote impredecible.',
    ],
    reps: '10 caídas por variante, 3 variantes por sesión',
    coachingCues: [
      'Mira la mano, no la pelota. La mano se mueve primero.',
      'Primer paso grande y bajo, luego ajusta con pasos cortos.',
      'Mantente en la punta de los pies en posición de espera, talones despegados del suelo.',
    ],
  },
  {
    id: 'ladder-basics',
    name: 'Escalera básica',
    section: 'coordination',
    level: 'beginner',
    goal: 'Construir ritmo, velocidad de pies y la capacidad de colocar los pies con precisión sin mirarlos.',
    equipment: 'Escalera de agilidad, o líneas de tiza a unos 45 centímetros de distancia',
    setup: 'Extiende la escalera a lo largo de la línea de fondo o perpendicular a la red. Empieza en un extremo en posición de espera.',
    steps: [
      'Un pie en cada cuadro: primero caminando, luego trotando, luego corriendo. Aterriza sobre la punta de los pies.',
      'Dos pies en cada cuadro: derecho dentro, izquierdo dentro, pasa al siguiente cuadro. Pasos rápidos y ligeros.',
      'Dentro-dentro-fuera-fuera: ambos pies dentro de un cuadro uno tras otro, luego ambos pies fuera hacia el costado del siguiente cuadro, y repite.',
      'Icky shuffle: pie derecho dentro del cuadro, pie izquierdo dentro, pie derecho fuera hacia la derecha. Luego izquierdo dentro, derecho dentro, izquierdo fuera hacia la izquierda. Sigue alternando.',
      'Dos dentro lateral: mírate de lado a la escalera y mete ambos pies en cada cuadro avanzando por la escalera.',
      'Termina cada recorrido con un split step y un golpe simulado al final de la escalera.',
    ],
    reps: '3 recorridos de cada patrón, vuelve caminando como descanso',
    coachingCues: [
      'Ritmo antes que velocidad. Di el patrón en voz alta mientras avanzas.',
      'Ojos arriba. Confía en tus pies y mira hacia la red.',
      'Los brazos también se mueven, codos flexionados como un velocista.',
      'Mantente bajo, no levantes las rodillas de más.',
    ],
  },

  // ---------------------------------------------------------- condición física
  {
    id: 'lateral-lunge-series',
    name: 'Serie de zancadas laterales',
    section: 'fitness',
    level: 'intermediate',
    goal: 'Fortalecer caderas y piernas en las posiciones laterales que el tenis exige, para que las pelotas abiertas y las frenadas fuertes no te cuesten las rodillas ni los tobillos.',
    equipment: 'Peso corporal para empezar, una mancuerna ligera o balón medicinal más adelante',
    setup: 'Una superficie plana con dos metros de espacio a cada lado. Calienta antes con dos minutos de saltos suaves a la cuerda o trote.',
    steps: [
      'Zancada lateral: da un paso amplio a la derecha, lleva las caderas atrás y abajo sobre el pie derecho, pierna izquierda recta. Empuja para volver a estar de pie. Ocho por lado.',
      'Zancada lateral con alcance: la misma zancada, pero lleva ambas manos hacia el pie exterior como si recogieras una pelota baja.',
      'Sentadilla cosaca: desde una posición amplia, pasa todo el peso a una pierna y baja lo más que puedas, el otro talón en el suelo con la punta arriba. Seis por lado.',
      'Zancada de reverencia: lleva el pie derecho por detrás y cruzando el izquierdo, flexiona ambas rodillas, vuelve. Ocho por lado.',
      'Salto lateral con fijación: salta de lado desde una pierna, aterriza en la otra y mantén el aterrizaje dos segundos. Seis por lado.',
      'Termina con una zancada lateral isométrica de 20 segundos por lado.',
    ],
    reps: '2 a 3 rondas, 60 segundos de descanso entre rondas, dos veces por semana',
    coachingCues: [
      'La rodilla sigue la línea del centro del pie, nunca se hunde hacia adentro.',
      'Lleva las caderas atrás como si cargaras para una derecha abierta.',
      'Pecho arriba, columna larga. No te dobles hacia adelante.',
      'Fija cada aterrizaje antes de volver a moverte.',
    ],
  },
  {
    id: 'medicine-ball-rotational-throws',
    name: 'Lanzamientos rotacionales con balón medicinal',
    section: 'fitness',
    level: 'intermediate',
    goal: 'Entrenar piernas, caderas y tronco para producir y transferir potencia rotacional en la misma secuencia que un golpe de fondo.',
    equipment: 'Balón medicinal de 2 a 4 kilogramos y una pared sólida, o un compañero',
    setup: 'Párate de lado a la pared a unos dos metros en una posición de derecha semiabierta.',
    steps: [
      'Lanzamiento de derecha: sostén el balón a la altura de la cadera en tu lado derecho, carga en la pierna derecha, luego rota primero caderas, después hombros, y lanza el balón contra la pared. Atrapa el rebote y repite. Ocho lanzamientos.',
      'Lanzamiento de revés: date vuelta y repite desde el otro lado, imitando un revés a dos manos. Ocho lanzamientos.',
      'Lanzamiento en posición abierta: pies paralelos a la pared, carga por completo la pierna exterior y lanza con rotación pura. Seis por lado.',
      'Paso y lanzamiento: empieza un metro más atrás, da un paso a posición neutra y lanza mientras transfieres el peso. Seis por lado.',
      'Golpe por encima de la cabeza: eleva el balón sobre la cabeza, extiéndete desde las piernas y estréllalo contra el suelo. Ocho golpes.',
      'Descansa 90 segundos y repite toda la serie.',
    ],
    reps: '3 series, 8 lanzamientos por patrón, dos veces por semana en días sin partido',
    coachingCues: [
      'Piernas y caderas inician el lanzamiento. Los brazos son lo último que se mueve.',
      'Mantente equilibrado tras soltar, igual que en la terminación de una derecha.',
      'Lanza fuerte pero con control. Si pierdes la forma, el balón pesa demasiado.',
      'Recuperación completa entre series. Esto es trabajo de potencia, no de resistencia.',
    ],
  },
  {
    id: 'skipping-intervals',
    name: 'Intervalos de salto a la cuerda',
    section: 'fitness',
    level: 'intermediate',
    goal: 'Desarrollar pies rápidos y elásticos y resistencia de pantorrillas y tobillos con una actividad que cabe en cualquier calentamiento o sesión de acondicionamiento.',
    equipment: 'Una cuerda de saltar cuyo largo haga que los mangos lleguen a tus axilas cuando pisas el medio',
    setup: 'Una superficie plana, idealmente la cancha o un piso con amortiguación en lugar de hormigón.',
    steps: [
      'Dos minutos de salto suave a dos pies para calentar.',
      '30 segundos de salto rápido a dos pies, 30 segundos lento. Cuatro rondas.',
      '30 segundos de saltos alternando una pierna, 30 segundos lento. Cuatro rondas.',
      '30 segundos de saltos de lado a lado: salta unos centímetros a izquierda y derecha sobre una línea imaginaria. 30 segundos lento. Cuatro rondas.',
      '20 segundos de dobles si puedes, si no a máxima velocidad. 40 segundos lento. Tres rondas.',
      'Termina con un minuto de salto suave y algunos estiramientos de pantorrilla.',
    ],
    reps: '15 a 18 minutos en total, 2 a 3 veces por semana',
    coachingCues: [
      'Salta solo lo justo para que pase la cuerda. Saltos pequeños, aterrizajes silenciosos.',
      'Gira la cuerda desde las muñecas, los codos se quedan cerca del cuerpo.',
      'Aterriza sobre la punta de los pies con los talones apenas tocando.',
      'Mirada al frente y postura erguida.',
    ],
  },
  {
    id: 'shoulder-care-band-work',
    name: 'Cuidado del hombro con banda elástica',
    section: 'fitness',
    level: 'intermediate',
    goal: 'Mantener fuertes y equilibrados el manguito rotador y los músculos del omóplato, para que miles de saques no se conviertan en un hombro dolorido.',
    equipment: 'Una banda elástica ligera, un anclaje de puerta o un poste de la cerca',
    setup: 'Ancla la banda a la altura del codo. Hazlo antes de practicar saques o como rutina independiente.',
    steps: [
      'Rotación externa: codo pegado al costado, flexionado a 90 grados, rota el antebrazo hacia afuera contra la banda. 15 repeticiones lentas por brazo.',
      'Rotación interna: mira hacia el otro lado y rota el antebrazo hacia adentro. 15 repeticiones por brazo.',
      'Rotación externa a 90 grados: codo elevado a la altura del hombro, rota la mano hacia arriba y atrás hasta la posición de trofeo del saque. 12 repeticiones por brazo.',
      'Aperturas con banda: sostén la banda con ambas manos a la altura del hombro, sepárala hasta abrir los brazos, apretando los omóplatos. 15 repeticiones.',
      'Jalones a la cara: tira de la banda hacia tu cara con los codos altos, terminando con los pulgares junto a las orejas. 15 repeticiones.',
      'Y escapulares: ancla bajo, eleva ambos brazos arriba y afuera en forma de Y, pulgares arriba. 12 repeticiones.',
      'Añade trabajo de extensores de muñeca: flexiones de muñeca con la palma hacia abajo con la banda o una mancuerna ligera, 15 repeticiones. Es tu seguro contra el codo de tenista.',
    ],
    reps: '2 rondas, 3 a 4 veces por semana, más en semanas de mucho saque',
    coachingCues: [
      'Lento al ir, más lento al volver. Dos segundos en cada sentido.',
      'Banda ligera. Si estás forzando, la banda es demasiado dura para este trabajo.',
      'Omóplatos abajo y atrás antes de cada repetición.',
      'Sin encoger los hombros. El cuello se mantiene relajado.',
    ],
  },
  {
    id: 'tennis-specific-interval-runs',
    name: 'Carreras por intervalos específicas de tenis',
    section: 'fitness',
    level: 'advanced',
    goal: 'Acondicionar tu cuerpo para repetir esfuerzos cortos e intensos con descansos breves, imitando el ritmo real de los puntos y las pausas entre ellos.',
    equipment: 'Cuatro conos, un temporizador con pitidos audibles o una app de intervalos',
    setup: 'Conos en la marca central y en cada línea lateral de individuales sobre la línea de fondo, más uno en la T de saque. Un punto dura en promedio 5 a 8 segundos y tienes unos 20 segundos entre puntos, así que los intervalos siguen esa forma.',
    steps: [
      'Trabajo 20 segundos: esprinta del centro al cono de la línea lateral izquierda y vuelve, luego al cono derecho y vuelve, haciendo pasos laterales en los últimos dos metros cada vez. Sigue hasta el pitido.',
      'Descanso 20 segundos: camina despacio de vuelta al centro y respira, como harías entre puntos.',
      'Repite 8 intervalos. Eso es aproximadamente un juego.',
      'Toma un descanso de cambio de lado de 90 segundos, sentado o de pie sin moverte.',
      'Segundo juego: alterna el patrón. Esprinta a la T de saque y vuelve, luego lateral a una línea lateral y vuelve.',
      'Tercer juego: añade golpes simulados en cada cono para que los brazos también trabajen.',
      'Juega 3 a 5 juegos en total según tu condición. Anota cuántos toques de cono lograste en el último juego comparado con el primero.',
    ],
    reps: '3 a 5 juegos de 8 intervalos, una o dos veces por semana fuera de temporada',
    coachingCues: [
      'Cada repetición a intensidad de partido. Si trotas, estás entrenando para trotar.',
      'La desaceleración es el trabajo. Caderas bajas y pasos cortos en cada giro.',
      'Usa el descanso exactamente como entre puntos: caminar despacio, respirar hondo, reenfocar.',
      'Cuando la calidad caiga bruscamente, termina la sesión. Moverse mal bajo fatiga enseña a moverse mal.',
    ],
  },
]
