import type { Grip } from '../types'

// La numeración de biseles es para un diestro que sostiene la raqueta de canto
// con el bisel 1 arriba, contando en sentido horario visto desde el tapón del
// mango. Un zurdo refleja cada número (el bisel 2 pasa a ser el 8, el 3 el 7,
// y así sucesivamente).
export const GRIPS: Grip[] = [
  {
    id: 'continental',
    name: 'Continental',
    indexKnuckle: 2,
    heelPad: 2,
    strokes: ['serve', 'slice', 'forehand-volley', 'backhand-volley', 'smash', 'back-smash', 'drop-shot', 'tweener'],
    feel: 'La empuñadura de martillo. La cara de la raqueta queda ligeramente abierta, la muñeca tiene libertad para latiguear y la misma empuñadura cubre ambos lados del cuerpo, así que nunca necesitas cambiar en la red.',
    howToFind: 'Sostén la raqueta de canto como si fueras a clavar un clavo con el marco. El nudillo base del índice y la almohadilla del talón de la mano descansan ambos sobre el bisel 2, el bisel pequeño entre la parte superior y el lado derecho. Otra comprobación: la V entre pulgar e índice apunta al borde izquierdo del bisel superior. Dar la mano al mango te deja cerca.',
    pros: [
      'Permite que la muñeca prone en el saque, que es de donde salen la velocidad y el efecto',
      'Abre la cara de forma natural para el slice, las voleas y las dejadas',
      'Una sola empuñadura para ambas voleas, así que no hay nada que cambiar en un intercambio rápido',
      'La única empuñadura que hace posible un smash y un smash de espaldas correctos',
    ],
    cons: [
      'Débil para golpes de fondo con topspin: la cara está abierta, así que las pelotas altas cuestan de controlar',
      'Las derechas con esta empuñadura tienden a flotar o irse largas ante mucha velocidad',
      'Se siente incómoda las primeras semanas porque la cara de la raqueta no está donde el principiante la espera',
    ],
    usedBy: ['Todos los profesionales en el saque y la volea', 'Roger Federer (voleas, slice)', 'John McEnroe (derecha y todo lo demás)', 'Ash Barty (revés cortado)'],
  },
  {
    id: 'eastern-forehand',
    name: 'Este de derecha',
    indexKnuckle: 3,
    heelPad: 3,
    strokes: ['forehand', 'swing-volley', 'return', 'drop-shot'],
    feel: 'Una empuñadura de saludo. La palma queda detrás del mango, así que el contacto se siente sólido y la cara de la raqueta está casi vertical. Fácil para golpear plano, fácil para añadir algo de topspin y rápida para cambiar a continental.',
    howToFind: 'Apoya la raqueta plana sobre una mesa con las cuerdas mirando al techo y levántala por el mango como si le dieras la mano. El nudillo base del índice y la almohadilla del talón caen sobre el bisel 3, el lado derecho del mango. Tu palma queda ahora en el mismo plano que las cuerdas.',
    pros: [
      'La empuñadura más natural para un principiante: la cara queda perpendicular a la pelota en el contacto',
      'Cómoda en botes bajos y medios y en canchas rápidas',
      'La más fácil de aplanar para una definición o una volea con swing',
      'A un solo bisel de la continental, así que los cambios de empuñadura hacia la red son rápidos',
    ],
    cons: [
      'Sufre con pelotas altas y pesadas con topspin por encima del hombro',
      'Menos topspin natural que la semioeste, así que el margen sobre la red es más fino',
      'La muñeca puede volverse perezosa y abrir la cara tarde en un peloteo largo',
    ],
    usedBy: ['Roger Federer', 'Juan Martín del Potro', 'Pete Sampras', 'Steffi Graf', 'Grigor Dimitrov (entre este y semioeste)'],
  },
  {
    id: 'semi-western',
    name: 'Semioeste de derecha',
    indexKnuckle: 4,
    heelPad: 4,
    strokes: ['forehand', 'return', 'swing-volley'],
    feel: 'El estándar moderno. La mano queda parcialmente debajo del mango, así que la cara está ligeramente cerrada y el swing de abajo hacia arriba cepilla la parte posterior de la pelota. Topspin pesado con mucha velocidad y un buen punto de contacto entre la cintura y el pecho, algo adelante del cuerpo.',
    howToFind: 'Parte de la este de derecha (bisel 3) y gira la mano un bisel en sentido horario, de modo que el nudillo base del índice y la almohadilla del talón queden sobre el bisel 4, el bisel inferior derecho. O deja la raqueta con la cara hacia el suelo y levántala con naturalidad: la mayoría la toma en semioeste.',
    pros: [
      'El topspin natural te da un margen alto sobre la red y una pelota que salta hacia el rival',
      'Maneja con comodidad los botes altos en polvo de ladrillo y el topspin pesado',
      'Sigue siendo lo bastante flexible para aplanar una pelota corta',
      'La empuñadura que la mayoría de los entrenadores enseña desde la etapa de pelota naranja en adelante',
    ],
    cons: [
      'Las pelotas bajas y deslizantes (césped, slice) exigen una flexión profunda de rodillas',
      'A dos biseles de la continental, así que los cambios de empuñadura para volear requieren práctica',
      'Tienta a rotar de más la muñeca y a golpear corto con demasiado efecto',
    ],
    usedBy: ['Novak Djokovic', 'Rafael Nadal', 'Carlos Alcaraz', 'Jannik Sinner', 'Iga Świątek', 'Aryna Sabalenka'],
  },
  {
    id: 'western',
    name: 'Oeste de derecha',
    indexKnuckle: 5,
    heelPad: 5,
    strokes: ['forehand'],
    feel: 'La mano completamente debajo del mango, así que la cara está claramente cerrada. El punto de contacto queda más adelante y más alto, y el swing sube con inclinación pronunciada, produciendo un topspin muy pesado y un bote que salta de la cancha.',
    howToFind: 'Gira un bisel más allá de la semioeste para que el nudillo base del índice y la almohadilla del talón queden sobre el bisel 5, la parte inferior del mango. La palma ahora mira hacia arriba y las cuerdas miran al suelo cuando el brazo cuelga. Algunos entrenadores la llaman la empuñadura de sartén.',
    pros: [
      'Máximo topspin y máximo margen sobre la red',
      'Muy cómoda en pelotas a la altura del hombro, así que rinde en arcilla lenta y de bote alto',
      'Fácil para abrir ángulos cerrados porque la cara cerrada y el efecto bajan la pelota rápido',
    ],
    cons: [
      'Las pelotas bajas y el slice son un problema real: tienes que flexionar mucho y la cara sigue queriendo cerrarse',
      'A tres biseles de la continental, así que pasar a volea o slice es lento',
      'Cuesta aplanar; la pelota a menudo carece de penetración en canchas rápidas',
      'Mucha carga en muñeca y codo para jugadores jóvenes que la copian antes de tener la fuerza suficiente',
    ],
    usedBy: ['Jack Sock', 'Karen Khachanov', 'Kei Nishikori', 'Alberto Berasategui (famosamente extrema, golpeaba ambos lados con la misma cara)', 'Muchos juniors de polvo de ladrillo'],
  },
  {
    id: 'eastern-backhand',
    name: 'Este de revés',
    indexKnuckle: 1,
    heelPad: 1,
    strokes: ['backhand-one-handed', 'slice'],
    feel: 'La empuñadura estándar del revés a una mano con topspin. Los nudillos sobre el mango ponen el dorso de la mano detrás de la raqueta en el contacto, lo que da una sensación firme y sólida y una cara vertical para el topspin y los drives.',
    howToFind: 'Desde la continental, gira la mano un bisel en sentido antihorario para que el nudillo base del índice y la almohadilla del talón queden sobre el bisel 1, la parte plana superior del mango. Tus nudillos deberían mirar a la red cuando llevas la raqueta atrás, y el pulgar envuelve en diagonal la parte trasera como apoyo.',
    pros: [
      'Estructura fuerte para el revés a una mano: la mano queda detrás de la pelota en el contacto',
      'Fácil para atravesar la pelota con topspin o plano',
      'A solo un bisel de la continental, así que los cambios a slice y volea son rápidos',
    ],
    cons: [
      'Las pelotas por encima del hombro son difíciles; el revés a una mano tiene que adelantarse o cortar',
      'El punto de contacto debe estar bien adelante, así que la preparación tardía se castiga',
      'Requiere un antebrazo más fuerte que el revés a dos manos, algo que a los juniors les lleva tiempo desarrollar',
    ],
    usedBy: ['Roger Federer', 'Stan Wawrinka', 'Grigor Dimitrov', 'Stefanos Tsitsipas'],
  },
  {
    id: 'extreme-eastern-backhand',
    name: 'Este extrema de revés',
    indexKnuckle: 8,
    heelPad: 8,
    strokes: ['backhand-one-handed'],
    feel: 'Un revés a una mano con la mano girada más allá para que la cara quede más cerrada. La pelota puede tomarse más alta y la trayectoria del swing cepilla con inclinación pronunciada para un topspin pesado, a costa de un slice menos amable y una ventana de contacto más estrecha.',
    howToFind: 'Desde la este de revés (bisel 1), gira un bisel más en sentido antihorario para que el nudillo base del índice y la almohadilla del talón queden sobre el bisel 8, el bisel pequeño entre la parte superior y el lado izquierdo. La palma ahora queda parcialmente sobre el mango y las cuerdas miran algo hacia abajo cuando extiendes la raqueta al costado.',
    pros: [
      'Permite a un revés a una mano lidiar con pelotas a la altura del hombro y topspin pesado en arcilla',
      'Produce un topspin muy pesado, que da margen en los passing shots',
      'La cara cerrada lleva la pelota hacia arriba y por encima de forma natural desde un contacto bajo',
    ],
    cons: [
      'A dos biseles de la continental, así que el cambio a slice o volea es más lento',
      'Los drives planos pierden penetración y la pelota puede quedar corta',
      'El timing es crítico: un golpe tardío se va largo o a la red',
      'La carga en muñeca y antebrazo es alta, así que desarrolla fuerza antes de adoptarla',
    ],
    usedBy: ['Richard Gasquet', 'Dominic Thiem', 'Lorenzo Musetti', 'Justine Henin'],
  },
  {
    id: 'two-handed-backhand',
    name: 'Revés a dos manos',
    indexKnuckle: 2,
    heelPad: 2,
    strokes: ['backhand-two-handed', 'return'],
    feel: 'Dos manos comparten el trabajo: la mano inferior (dominante, derecha) en continental dirige y estabiliza, la mano superior (izquierda) en este de derecha hace la mayor parte del golpe. Se siente como una derecha de zurdo con la mano derecha acompañando.',
    howToFind: 'Primero la mano derecha: toma una empuñadura continental (bisel 2) en la parte baja del mango, como para una volea. Luego coloca la mano izquierda encima, en contacto, en una este de derecha para zurdo: nudillo base del índice izquierdo y almohadilla del talón sobre el bisel 7, que es la imagen espejo del bisel 3. Comprueba que la palma izquierda quede detrás del mango, mirando a la red en el contacto. Algunos jugadores usan la mano izquierda en semioeste (bisel 6) para más topspin, y otros giran la mano derecha a este de revés (bisel 1) para una muñeca más firme.',
    pros: [
      'Estable y potente, sobre todo para juniors y para quien no tiene un antebrazo fuerte',
      'Maneja bien las pelotas altas y la velocidad pesada: las dos manos actúan como palanca',
      'La mano derecha ya está en continental, así que pasar a slice o volea solo implica soltar con la izquierda',
      'Fácil de disimular y de golpear en carrera o con preparación corta en la devolución',
    ],
    cons: [
      'Menos alcance que el revés a una mano, así que las pelotas abiertas necesitan un paso extra o un slice a una mano',
      'Las pelotas bajas y cortas exigen mucha flexión porque las dos manos limitan cuánto puedes bajar la raqueta',
      'Los jugadores pueden volverse dependientes de él y descuidar el slice a una mano',
    ],
    usedBy: ['Novak Djokovic', 'Rafael Nadal', 'Andre Agassi', 'Iga Świątek', 'Serena Williams', 'Coco Gauff'],
  },
]
