import type { PathStage } from '../types'

// Once etapas desde nunca haber sostenido una raqueta hasta ser un jugador de
// toda la cancha a nivel de torneo. Los rangos son una guía aproximada en horas
// de cancha.

export const PATH: PathStage[] = [
  {
    n: 0,
    title: 'Primer contacto',
    range: '0–10 horas',
    who: 'Nunca has sostenido una raqueta, o lo intentaste una vez hace años y no recuerdas nada.',
    goals: [
      'Entender para qué sirven la cancha, las líneas y la red',
      'Sostener la raqueta con una empuñadura que funcione para una derecha básica',
      'Hacer que el centro de las cuerdas encuentre la pelota a propósito',
      'Saber cómo se gana y se pierde un punto',
    ],
    items: [
      { label: 'Aprende las líneas de la cancha y qué significa cada una', to: '/learn/courts' },
      { label: 'Descubre qué pelota deberías usar para empezar', to: '/learn/balls' },
      { label: 'Elige una raqueta adecuada para principiantes', to: '/learn/racquets' },
      { label: 'Aprende la empuñadura este de derecha y cómo encontrarla', to: '/learn/grips' },
      { label: 'Haz los ejercicios de bote y atrapa y de arriba y abajo', to: '/learn/footwork' },
      { label: 'Mira la derecha en cámara lenta', to: '/studio/forehand' },
      { label: 'Aprende cómo se cuentan los puntos', to: '/learn/scoring' },
    ],
    milestone: 'Bota la pelota contra el suelo con la raqueta 20 veces seguidas y luego pega 5 derechas autolanzadas por encima de la red dentro de la cancha.',
  },
  {
    n: 1,
    title: 'Listo para pelotear',
    range: '10–30 horas',
    who: 'Puedes pasar la pelota por encima de la red, pero un peloteo de más de tres pelotas parece cuestión de suerte.',
    goals: [
      'Pegar una derecha y un revés con una forma de swing repetible',
      'Adoptar la posición de espera y empezar a hacer el split step',
      'Moverte hacia la pelota y detenerte antes de golpear',
      'Pelotear de forma cooperativa por encima de la red con un compañero',
    ],
    items: [
      { label: 'Estudia el revés a dos manos', to: '/studio/backhand-two-handed' },
      { label: 'O, si te acomoda más, el revés a una mano', to: '/studio/backhand-one-handed' },
      { label: 'Aprende la posición de espera y el split step', to: '/studio/split-step' },
      { label: 'Practica la recuperación con pasos laterales y el ocho', to: '/learn/footwork' },
      { label: 'Lee por qué el juego de pies lo decide todo', to: '/learn/footwork' },
      { label: 'Aprende las reglas básicas: lets, faltas y quién saca', to: '/learn/rules' },
    ],
    milestone: 'Peloteo cooperativo cruzado de 20 pelotas con un compañero desde la línea de saque, usando derechas y reveses.',
  },
  {
    n: 2,
    title: 'Con cabeza en la cancha',
    range: '30–60 horas',
    who: 'Puedes pelotear corto y quieres jugar puntos de verdad, saque incluido.',
    goals: [
      'Sacar con empuñadura continental y un lanzamiento consistente',
      'Pelotear desde la línea de fondo con topspin y profundidad',
      'Llevar el marcador correctamente durante un juego y un set completos',
      'Recuperar hacia el centro después de cada pelota',
    ],
    items: [
      { label: 'Aprende el saque desde el lanzamiento', to: '/studio/serve' },
      { label: 'Encuentra la empuñadura continental', to: '/learn/grips' },
      { label: 'Haz los ejercicios de posición de espera, pasos laterales y paso cruzado', to: '/studio/shuffle' },
      { label: 'Aprende el conteo, los tie-breaks y los cambios de lado', to: '/learn/scoring' },
      { label: 'Lee las primeras tácticas: regularidad y profundidad', to: '/learn/tactics' },
      { label: 'Crea el hábito de calentar y enfriar', to: '/learn/fitness' },
    ],
    milestone: 'Meter 6 de 10 saques en el cuadro correcto desde la línea de fondo y jugar un set completo con el conteo correcto.',
  },
  {
    n: 3,
    title: 'Constructor de puntos',
    range: '60–120 horas',
    who: 'Juegas sets con regularidad y puedes pelotear desde el fondo, pero los puntos se sienten aleatorios y la red da miedo.',
    goals: [
      'Volear de ambos lados con empuñadura continental',
      'Pegar un revés cortado para defender y para subir',
      'Reconocer las cinco situaciones de juego y actuar en consecuencia',
      'Usar una rutina entre puntos',
    ],
    items: [
      { label: 'Aprende la volea de derecha', to: '/studio/forehand-volley' },
      { label: 'Aprende la volea de revés', to: '/studio/backhand-volley' },
      { label: 'Estudia el slice', to: '/studio/slice' },
      { label: 'Lee las cinco situaciones de juego', to: '/learn/tactics' },
      { label: 'Aprende la rutina entre puntos', to: '/learn/mental' },
      { label: 'Haz el ejercicio de subida y split', to: '/learn/footwork' },
      { label: 'Practica el paso cruzado para pelotas abiertas', to: '/studio/crossover' },
    ],
    milestone: 'Peloteo cooperativo de 50 pelotas desde la línea de fondo, y ganar un ejercicio de volea contra fondo metiendo 10 voleas seguidas dentro de la cancha.',
  },
  {
    n: 4,
    title: 'Sólido en todo',
    range: '120–200 horas',
    who: 'Tienes todos los golpes básicos y una pelota de peloteo fiable. Quieres dejar de perder contra jugadores que solo empujan la pelota.',
    goals: [
      'Pegar un segundo saque fiable con efecto',
      'Jugar el remate con confianza',
      'Devolver primeros y segundos saques con intenciones distintas',
      'Entender las posiciones de pies y golpear desde la pierna exterior',
    ],
    items: [
      { label: 'Estudia el smash y el juego de pies del paso atrás', to: '/studio/smash' },
      { label: 'Aprende a leer y devolver saques', to: '/studio/return' },
      { label: 'Lee la explicación de las posiciones de pies', to: '/learn/footwork' },
      { label: 'Haz el ejercicio de la araña y anota tu tiempo', to: '/learn/footwork' },
      { label: 'Lee fuerza para el tenis y empieza sesiones dos veces por semana', to: '/learn/fitness' },
      { label: 'Lee patrones de juego: saque más uno', to: '/learn/tactics' },
    ],
    milestone: 'Meter 7 de 10 segundos saques con efecto, 5 de 10 remates dentro de la cancha desde un globo lanzado, y ganar un set de práctica contra un jugador que solo empuja.',
  },
  {
    n: 5,
    title: 'Competidor',
    range: '200–350 horas',
    who: 'Juegas partidos de club o ligas internas y ganas más o menos tanto como pierdes. Quieres ser un jugador de partido en vez de un pegador.',
    goals: [
      'Jugar al menos dos patrones de juego a propósito',
      'Cambiar de dirección solo con la pelota correcta',
      'Manejar los nervios en los puntos grandes con un plan',
      'Jugar dobles con la colocación correcta',
    ],
    items: [
      { label: 'Lee patrones de juego y elige dos para hacerlos tuyos', to: '/learn/tactics' },
      { label: 'Lee cómo manejar los nervios y los bloqueos', to: '/learn/mental' },
      { label: 'Lee los fundamentos de la táctica de dobles', to: '/learn/tactics' },
      { label: 'Haz saque más uno y recuperación y el triángulo de conos', to: '/learn/footwork' },
      { label: 'Empieza las carreras por intervalos específicas de tenis', to: '/learn/fitness' },
      { label: 'Aprende la dejada como cambio de ritmo', to: '/studio/drop-shot' },
      { label: 'Lleva un diario de entrenamiento: practica con propósito', to: '/learn/mental' },
    ],
    milestone: 'Ganar un set en un partido competitivo usando el patrón de saque más uno al menos cinco veces, y meter 8 de 10 pelotas cruzadas más allá de la línea de saque bajo presión de peloteo.',
  },
  {
    n: 6,
    title: 'Constructor de armas',
    range: '350–500 horas',
    who: 'Compites con regularidad y te defiendes bien. Ahora necesitas un golpe que gane puntos, no solo un juego que evite perderlos.',
    goals: [
      'Desarrollar un arma: un saque, una derecha o una devolución que los rivales teman',
      'Usar el patrón de derecha invertida',
      'Atacar las pelotas cortas con una volea con swing o una subida',
      'Leer la raqueta del rival para anticipar temprano',
    ],
    items: [
      { label: 'Estudia la volea con swing', to: '/studio/swing-volley' },
      { label: 'Refina el saque: efecto, colocación, disimulo', to: '/studio/serve' },
      { label: 'Compara tu derecha con la de los profesionales', to: '/pros' },
      { label: 'Lanzamientos con balón medicinal y serie de zancadas laterales', to: '/learn/fitness' },
      { label: 'Lee recuperación y colocación en la cancha', to: '/learn/footwork' },
      { label: 'Lee cómo aprender un golpe y grábate en video', to: '/learn/mental' },
    ],
    milestone: 'Meter 6 de 10 primeros saques en la mitad del cuadro que te indiquen, y ganar el 60 % de los puntos de práctica que empiezan con una pelota corta que atacas.',
  },
  {
    n: 7,
    title: 'Táctico',
    range: '500–750 horas',
    who: 'Tienes un arma y un plan de juego. Quieres ganarle a jugadores que técnicamente son tan buenos como tú.',
    goals: [
      'Adaptar la táctica al rival, la superficie y las condiciones',
      'Variar efecto, altura y velocidad a propósito',
      'Defender desde detrás de la línea de fondo y neutralizar el punto',
      'Jugar en la red en individuales cuando la subida es la correcta',
    ],
    items: [
      { label: 'Estudia el smash de espaldas para los globos que te pasan', to: '/studio/back-smash' },
      { label: 'Repasa el slice para defender y subir', to: '/studio/slice' },
      { label: 'Aprende cómo las superficies cambian el juego', to: '/learn/courts' },
      { label: 'Lee resistencia y velocidad y arma un plan semanal', to: '/learn/fitness' },
      { label: 'Lee moverse hacia adelante y hacia atrás', to: '/learn/footwork' },
      { label: 'Estudia cómo construyen los puntos los profesionales', to: '/pros' },
    ],
    milestone: 'Ganar un partido cambiando el plan de juego a mitad del partido y anotar en tu diario qué cambiaste y por qué. Ejercicio de la araña en menos de 18 segundos.',
  },
  {
    n: 8,
    title: 'Duro en torneos',
    range: '750–1,000 horas',
    who: 'Juegas torneos oficiales o ligas de alto nivel. Pierdes sobre todo por nervios, fatiga o una debilidad que te descubren.',
    goals: [
      'Jugar partidos a tres sets con intensidad constante',
      'Mantener el saque bajo presión con un segundo saque fiable',
      'Eliminar el único golpe al que apuntan los rivales',
      'Ejecutar de forma automática una rutina completa entre puntos y en los cambios de lado',
    ],
    items: [
      { label: 'Audita cada golpe contra los modelos', to: '/studio/backhand-two-handed' },
      { label: 'Práctica de devolución: bloqueo, chip y drive', to: '/studio/return' },
      { label: 'Cuidado del hombro con banda como rutina diaria', to: '/learn/fitness' },
      { label: 'Entrenamiento mental: rutinas y práctica bajo presión', to: '/learn/mental' },
      { label: 'Conoce las reglas de torneo y el arbitraje', to: '/learn/rules' },
      { label: 'Revisa tus elecciones de raqueta, cuerda y tensión', to: '/learn/racquets' },
    ],
    milestone: 'Meter 7 de 10 segundos saques en el blanco de la esquina del revés en un escenario de 30-30, y completar un partido de práctica a tres sets con tu porcentaje de primeros saques por encima del 60 % en cada set.',
  },
  {
    n: 9,
    title: 'Jugador de toda la cancha',
    range: '1,000–1,500 horas',
    who: 'Ganas partidos de torneo y te sientes cómodo en cualquier zona de la cancha. Quieres los toques finales.',
    goals: [
      'Definir los puntos en la red desde cualquier subida',
      'Jugar dejadas y globos como opciones tácticas reales',
      'Usar el tweener o el smash de espaldas cuando un globo realmente te supera',
      'Ser tu propio entrenador: diagnosticar y corregir tu juego entre clases',
    ],
    items: [
      { label: 'Refina la dejada y disimúlala', to: '/studio/drop-shot' },
      { label: 'Estudia el tweener para el globo desesperado', to: '/studio/tweener' },
      { label: 'Estudia el smash de espaldas', to: '/studio/back-smash' },
      { label: 'Compara tus patrones de movimiento con los profesionales', to: '/pros' },
      { label: 'Repasa la táctica de dobles para eventos por equipos', to: '/learn/tactics' },
      { label: 'Programa completo de fuerza y acondicionamiento', to: '/learn/fitness' },
    ],
    milestone: 'Ganar un set de práctica en el que cada punto que ganes venga de una subida a la red, y ganar un partido de torneo usando al menos tres patrones de juego distintos.',
  },
  {
    n: 10,
    title: 'Jugador completo',
    range: '1,500+ horas',
    who: 'Eres un jugador de toda la cancha a nivel de torneo. La mejora ahora viene del detalle, la periodización y mantenerte sano.',
    goals: [
      'Periodizar la temporada: construir, competir, recuperar',
      'Mantener cada golpe con revisión regular de video',
      'Evitar lesiones con una rutina estructurada de prevención',
      'Devolver algo: ayudar a un jugador de menor nivel a recorrer el camino',
    ],
    items: [
      { label: 'Revisión cuadro a cuadro del saque contra los profesionales', to: '/studio/serve' },
      { label: 'Comparación con profesionales en cada golpe', to: '/pros' },
      { label: 'Planifica la temporada con bloques de fuerza, velocidad y recuperación', to: '/learn/fitness' },
      { label: 'Refina el juego mental para torneos largos', to: '/learn/mental' },
      { label: 'Mantén el juego de pies afilado con ejercicios de la araña cronometrados', to: '/learn/footwork' },
      { label: 'Mantente al día con las reglas y la normativa de equipamiento', to: '/learn/rules' },
    ],
    milestone: 'Completar una temporada de torneos con un plan escrito, un diario de partido para cada partido y sin tiempo perdido por lesiones prevenibles. Ejercicio de la araña en menos de 16 segundos.',
  },
]
