import type { JuniorSize, RacquetSpec } from '../types'

export const RACQUET_TYPES: RacquetSpec[] = [
  {
    id: 'power-oversize',
    name: 'Potencia / oversize',
    headSize: '105–118 sq in (677–761 cm²)',
    weight: '230–275 g sin encordar, a menudo 27,5 in (69,9 cm) de largo',
    balance: 'Balance a la cabeza, 2–6 pts HH (35–37 cm desde el tapón)',
    stiffness: 'Rígida, RA 68–75, perfil ancho de 26–30 mm',
    stringPattern: '16x19 o abierto 16x18',
    forWhom: 'Principiantes con swings cortos y lentos, seniors y jugadores que quieren profundidad gratis sin esfuerzo. Head Ti.S6 (115 sq in, 225 g), Wilson Clash 108, Babolat Boost Drive y Prince Ripstick 105 son típicas.',
    feel: 'Como un trampolín. El enorme punto dulce perdona los golpes descentrados y el marco ligero es fácil de mover, pero la configuración rígida y con balance a la cabeza transmite vibración al brazo y, cuando tu swing se acelera, la pelota empieza a irse larga.',
  },
  {
    id: 'tweener-all-round',
    name: 'Tweener / polivalente',
    headSize: '98–102 sq in, casi siempre 100 sq in (645 cm²)',
    weight: '280–305 g sin encordar, 27 in (68,6 cm) de largo',
    balance: 'Ligeramente al mango, 4–7 pts HL (32–33 cm)',
    stiffness: 'Media-rígida, RA 63–72, perfil de 22–26 mm',
    stringPattern: '16x19',
    forWhom: 'La categoría más grande con diferencia, desde principiantes en progreso hasta jugadores de club avanzados. Babolat Pure Drive y Pure Aero, Wilson Blade 100, Head Speed MP, Yonex EZONE 100 y Tecnifibre TF-X1 son todas tweeners.',
    feel: 'Equilibrada entre potencia y control, con efecto fácil gracias al patrón abierto. Suficiente masa para ser estable ante la velocidad, lo bastante ligera para moverla rápido. Si no sabes qué quieres, empieza aquí.',
  },
  {
    id: 'modern-players',
    name: 'Raqueta de jugador moderna',
    headSize: '97–100 sq in (626–645 cm²)',
    weight: '300–315 g sin encordar',
    balance: 'Al mango, 6–9 pts HL (31–32,5 cm), swingweight 320–335',
    stiffness: 'Media, RA 60–68, perfil de 21–23 mm',
    stringPattern: '16x19 (algunas versiones 18x20)',
    forWhom: 'Juniors avanzados y adultos con swings completos y rápidos que generan su propia potencia y quieren sensación y control a alta velocidad de cabeza de raqueta. Wilson Blade 98, Head Gravity MP y Pro, Babolat Pure Strike 98 y Yonex VCORE 98 son ejemplos.',
    feel: 'Suave y conectada. El perfil flexible y más fino te da información en cada golpe, y la masa extra atraviesa las pelotas pesadas. Tú debes aportar la velocidad de swing; un swing corto produce una pelota corta.',
  },
  {
    id: 'classic-control',
    name: 'Raqueta clásica de control',
    headSize: '93–98 sq in (600–632 cm²)',
    weight: '310–340 g sin encordar',
    balance: 'Muy al mango, 8–12 pts HL (30,5–32 cm), swingweight 325–345',
    stiffness: 'Flexible, RA 58–65, perfil de 17–21 mm',
    stringPattern: '18x20 o 16x19 denso',
    forWhom: 'Jugadores experimentados con golpes largos y técnicamente sólidos que valoran la precisión y el golpe plano por encima del efecto y la potencia gratis. Wilson Pro Staff 97 y RF 97, Head Prestige Pro y Prince Phantom 93P están aquí, como lo estaba la Pro Staff 6.0 de 85 sq in de la era Sampras.',
    feel: 'Precisa y sólida pero sin perdón. La cabeza pequeña y el patrón denso te permiten hacer el swing a toda velocidad y apuntar a las líneas, pero los golpes descentrados pierden potencia rápido y el marco pesado cansa a lo largo de tres sets si no tienes la condición física.',
  },
  {
    id: 'junior-aluminium',
    name: 'Junior de aluminio',
    headSize: '80–100 sq in (516–645 cm²)',
    weight: '170–240 g encordada según la longitud',
    balance: 'Balance aproximadamente neutro para la mano de un niño',
    stiffness: 'Marco de aluminio, sin clasificación RA; los marcos junior de compuesto de grafito empiezan alrededor de 25 in',
    stringPattern: '16x17 a 16x19, encordada de fábrica',
    forWhom: 'Niños de 4 a unos 10 años en longitudes de 19, 21, 23 y 25 in, ajustadas a las etapas de pelota roja y naranja. Babolat Ballfighter, Head Speed Jr, Wilson US Open Jr y Yonex EZONE Jr son típicas y cuestan 20–40 euros.',
    feel: 'Ligera, viva y lo bastante resistente para sobrevivir a las caídas. El aluminio y las cuerdas de fábrica se sienten algo muertos, lo que no importa en esta etapa. Pasa a un marco de grafito de 25 o 26 in cuando el niño llegue a la pelota verde y empiece a generar su propio efecto.',
  },
]

export const JUNIOR_SIZES: JuniorSize[] = [
  { length: '19 in (48 cm)', ageRange: '4 años o menos', heightRange: 'hasta 100 cm (3 ft 3 in)', ballStage: 'Roja (etapa 3), espuma y luego fieltro' },
  { length: '21 in (53 cm)', ageRange: '4–5 años', heightRange: '100–115 cm (3 ft 3 in – 3 ft 9 in)', ballStage: 'Roja (etapa 3)' },
  { length: '23 in (58 cm)', ageRange: '6–8 años', heightRange: '115–125 cm (3 ft 9 in – 4 ft 1 in)', ballStage: 'Roja pasando a naranja (etapa 2)' },
  { length: '25 in (63,5 cm)', ageRange: '9–10 años', heightRange: '125–140 cm (4 ft 1 in – 4 ft 7 in)', ballStage: 'Naranja (etapa 2) pasando a verde' },
  { length: '26 in (66 cm)', ageRange: '10–11 años', heightRange: '140–150 cm (4 ft 7 in – 4 ft 11 in)', ballStage: 'Verde (etapa 1)' },
  { length: '27 in (68,6 cm), adulto', ageRange: '11–12 años en adelante', heightRange: '150 cm (4 ft 11 in) o más', ballStage: 'Verde y luego amarilla estándar' },
]

export const STRING_TYPES: { id: string; name: string; feel: string; durability: string; forWhom: string; tension: string }[] = [
  {
    id: 'natural-gut',
    name: 'Tripa natural',
    feel: 'La referencia. Hecha de hebras trenzadas de serosa de intestino vacuno, es la cuerda más elástica que existe: blanda, potente, viva y extraordinariamente buena manteniendo la tensión. Babolat VS Touch y Wilson Natural Gut son las referencias.',
    durability: 'Moderada para una cuerda blanda, pero odia la humedad y se deshilacha rápido con mucho efecto. Cara: 40–55 euros el set.',
    forWhom: 'Jugadores con problemas de brazo, jugadores que quieren la máxima sensación, y como cuerdas verticales en un híbrido al estilo profesional con poliéster en las horizontales.',
    tension: '23–27 kg (50–60 lb). Se mantiene cerca de esa tensión durante semanas.',
  },
  {
    id: 'multifilament',
    name: 'Multifilamento',
    feel: 'Cientos o miles de microfibras finas de nailon agrupadas para imitar la tripa. Blanda, cómoda y potente, con buena absorción de impactos. Tecnifibre X-One Biphase, Wilson NXT y Head Velocity MLT son las elecciones habituales.',
    durability: 'Baja a moderada; las fibras externas se deshilachan y la cuerda se rompe cuando se han cortado suficientes. Pierde tensión de forma constante a lo largo de 4–8 semanas.',
    forWhom: 'Principiantes y jugadores de club que buscan comodidad, cualquiera con codo de tenista y jugadores planos que no rompen cuerdas a menudo.',
    tension: '23–26 kg (50–57 lb). No bajes demasiado o la pelota se vuela.',
  },
  {
    id: 'synthetic-gut',
    name: 'Tripa sintética',
    feel: 'Un núcleo sólido de nailon con una o más capas exteriores. Crujiente, de firmeza media y sin nada especial, lo cual es un cumplido: hace todo de forma adecuada. Prince Synthetic Gut Duraflex y Gosen OG Sheep Micro son clásicos y cuestan 4–8 euros el set.',
    durability: 'Decente para una cuerda de nailon y la opción más barata con diferencia, por eso la mayoría de las raquetas encordadas de fábrica la traen.',
    forWhom: 'Principiantes, jugadores con presupuesto ajustado y juniors que gastan muchas cuerdas. Una buena elección hasta que sepas lo que te estás perdiendo.',
    tension: '23–26 kg (50–57 lb).',
  },
  {
    id: 'polyester',
    name: 'Poliéster (poli)',
    feel: 'Un único monofilamento rígido de poliéster o copoliéster. Poca potencia, mucho control, y las cuerdas vuelven a su sitio de golpe en el contacto, que es de donde sale el topspin pesado moderno. Luxilon ALU Power, Babolat RPM Blast y Solinco Hyper-G dominan el circuito.',
    durability: 'Extremadamente difícil de romper, pero el poli pierde tensión rápido y se vuelve muerto y acartonado mucho antes de romperse, normalmente a las 10–20 horas de juego. Córtalo en vez de esperar a que se rompa.',
    forWhom: 'Jugadores avanzados y juniors fuertes que hacen swings rápidos, pegan con mucho efecto y rompen rápido las cuerdas blandas. No para principiantes, no para quien tenga dolor de brazo y no recomendado por debajo de unos 13 años.',
    tension: '20–25 kg (44–55 lb), normalmente 2–4 kg menos de lo que encordarías un nailon.',
  },
  {
    id: 'hybrid',
    name: 'Híbrido',
    feel: 'Dos cuerdas distintas: una en las verticales y otra en las horizontales. Tripa o multifilamento en las verticales con poli en las horizontales da comodidad y potencia con efecto y durabilidad extra; poli en las verticales con una cuerda más blanda en las horizontales da el control del poli con algo más de comodidad. Federer usaba tripa natural en las verticales con Luxilon ALU Power Rough en las horizontales.',
    durability: 'Mejor que la cuerda blanda sola porque el poli la protege en una dirección. Las dos cuerdas pierden tensión a ritmos distintos, así que reencorda cuando cualquiera de las dos se sienta mal.',
    forWhom: 'Jugadores intermedios y avanzados que buscan un compromiso, y rompedores de cuerdas a quienes el poli completo les resulta demasiado duro.',
    tension: 'Encorda el poli 1–2 kg por debajo de la cuerda más blanda, por ejemplo 24 kg de tripa en las verticales y 22 kg de poli en las horizontales.',
  },
]
