import type { Surface } from '../types'

export const SURFACES: Surface[] = [
  {
    id: 'hard',
    name: 'Cancha dura',
    speed: 3,
    bounce: 3,
    typicalRally: 'Intercambios medios de 4–8 golpes. El bote es parejo y predecible, así que los peloteos desde el fondo son rápidos y fieles, y un gran saque más un golpe de fondo sólido ganan muchos puntos.',
    famousFor: 'El Abierto de Australia (GreenSet desde 2020, Plexicushion antes) y el US Open (Laykold desde 2020, DecoTurf antes). La mayoría de las canchas públicas de Norteamérica, Asia y Australia son duras.',
    construction: 'Base de asfalto u hormigón y luego varias capas de resina acrílica. La capa de color se mezcla con arena de sílice: más arena y granos más gruesos hacen la cancha más lenta, menos arena la acelera. Los sistemas amortiguados como Laykold Masters o Plexicushion añaden capas de goma bajo el acrílico para suavizar el impacto. La clasificación ITF de velocidad (Court Pace Rating) de las canchas duras del circuito suele estar en la categoría 3 (media, 35–39) o 4 (media-rápida, 40–44).',
    playingStyle: 'La superficie todoterreno. El saque y el primer golpe funcionan porque el bote es fiable y algo deslizante. Los jugadores planos y los grandes sacadores ganan; el topspin pesado sigue saltando, pero no tanto como en polvo de ladrillo. Los puntos terminan más rápido que en arcilla, así que toma la iniciativa en vez de esperar errores.',
    footwear: 'Zapatillas para toda superficie con suela duradera en espiga o modificada y buen soporte lateral. Las canchas duras devoran las suelas, así que busca una garantía de suela de seis meses. Una mediasuela más firme protege el pie de una superficie que no perdona.',
    bodyNote: 'La superficie más dura para el cuerpo. Las frenadas son bruscas y no hay absorción, así que rodillas, tibias y zona lumbar reciben carga repetida. Calienta bien, limita las sesiones largas seguidas cuando empiezas y considera las canchas acrílicas amortiguadas como un regalo.',
  },
  {
    id: 'clay',
    name: 'Cancha de polvo de ladrillo',
    speed: 1,
    bounce: 5,
    typicalRally: 'Intercambios largos de 8–15 golpes o más. La capa superior suelta agarra la pelota, le quita velocidad y eleva el bote, así que los tiros ganadores cuestan y lo que más pesa es la regularidad y la construcción del punto.',
    famousFor: 'Roland Garros (polvo de ladrillo rojo), los Masters de Montecarlo, Roma y Madrid, y la arcilla verde Har-Tru en Estados Unidos. La mayoría de las canchas de club en España, Italia, Francia, Argentina y Alemania son de polvo de ladrillo.',
    construction: 'Las canchas de Roland Garros tienen cinco capas de unos 80 cm de profundidad: piedras grandes, luego unos 30 cm de grava, después unos 7–8 cm de escoria (residuo de carbón que retiene la humedad), luego 6–7 cm de caliza blanca finamente triturada y, por último, apenas 1–2 mm de ladrillo rojo molido espolvoreado encima. El ladrillo es lo que ves y sobre lo que deslizas; la caliza de debajo es la verdadera superficie de juego. La arcilla verde (Har-Tru) usa metabasalto triturado, drena más rápido y juega algo más veloz. Las canchas se riegan y apisonan a diario.',
    playingStyle: 'Paciencia, topspin pesado y profundidad. Los botes más altos premian a quien golpea cómodo por encima del hombro, así que las empuñaduras semioeste y oeste brillan. Las dejadas funcionan porque los rivales se quedan atrás. Aprende a deslizar hacia la pelota y recuperar en lugar de frenar y arrancar. El saque y volea es raro; los saques planos pierden su mordiente.',
    footwear: 'Zapatillas específicas de arcilla con suela completa en espiga (zigzag) que agarra al plantar y suelta al deslizar, más una malla superior más cerrada que mantiene el polvo fuera. Una suela lisa en polvo de ladrillo es peligrosa.',
    bodyNote: 'La superficie más amable con las articulaciones porque la capa superior cede en cada paso. Los peloteos largos ponen a prueba la resistencia aeróbica y las piernas, y deslizar exige cosas nuevas a caderas y aductores, así que añade trabajo de movilidad de cadera. Cuenta con polvo rojo en calcetines, zapatillas y pelota.',
  },
  {
    id: 'grass',
    name: 'Cancha de césped',
    speed: 5,
    bounce: 1,
    typicalRally: 'Intercambios cortos de 2–5 golpes. La pelota se desliza baja y rápida, sobre todo la primera semana cuando el césped está espeso, así que el saque, la devolución y la primera volea deciden la mayoría de los puntos.',
    famousFor: 'Wimbledon y la corta gira de césped que lo precede (Queen’s Club, Halle, Eastbourne, Stuttgart, Berlín, ’s-Hertogenbosch). Las canchas de césped son raras fuera de Gran Bretaña, Alemania, Países Bajos y Australia porque cuesta mucho mantenerlas.',
    construction: 'Las canchas de Wimbledon son 100 % ryegrass perenne desde 2001 (reemplazó una mezcla 70/30 de ryegrass y festuca roja por durabilidad) y se cortan exactamente a 8 mm cada día del torneo. El césped crece sobre una base firme y compactada de arcilla franca, apisonada hasta una dureza comparable a la de una cancha dura; la firmeza del suelo, no el césped, fija la velocidad. Las canchas se resiembran cada otoño y, para la segunda semana del torneo, la zona de la línea de fondo está desgastada, marrón, y juega más alta y lenta.',
    playingStyle: 'Ataca. Saca fuerte y sube tras el saque, haz chip y sube en la devolución y mantén tu slice bajo porque la pelota igual se queda baja. Flexiona las rodillas más que en cualquier otra superficie: muchos puntos de contacto quedan por debajo de la rodilla. El apoyo es menos seguro, así que acorta los pasos y quédate bajo en vez de esprintar a tope. Los botes con topspin se amortiguan, así que los jugadores planos y de slice salen ganando.',
    footwear: 'Las zapatillas de césped tienen suela de goma con tacos pequeños o puntitos para agarrar en el pasto. La mayoría de los clubes prohíbe cualquier otra porque la espiga rompe la superficie. Algunos torneos permiten zapatillas para toda superficie cuando el césped está seco.',
    bodyNote: 'Blando bajo el pie y suave con las articulaciones, pero resbalar es el riesgo principal, sobre todo detrás de la línea de fondo en una mañana húmeda. Los botes bajos cargan cuádriceps y zona lumbar por las flexiones profundas constantes. Muévete con pasos cortos y nunca plantes el pie plano al girar.',
  },
  {
    id: 'indoor',
    name: 'Cancha cubierta',
    speed: 4,
    bounce: 2,
    typicalRally: 'Intercambios medio-cortos de 3–7 golpes. Sin viento, sin sol y con iluminación controlada, la pelota vuela fiel, así que el saque y el juego agresivo desde el fondo prosperan y baja la tasa de errores.',
    famousFor: 'Las ATP Finals (Turín), el Masters de París, Róterdam, Viena y Basilea, además de las Finales de la Copa Davis. La mayoría de los torneos de otoño del circuito se juegan en cancha dura cubierta. La alfombra (Supreme, Taraflex) fue habitual bajo techo hasta que la ATP la retiró del circuito en 2009; algunos clubes aún la tienen.',
    construction: 'Normalmente una cancha dura acrílica sobre hormigón o sobre un piso de madera elevado (GreenSet, Rebound Ace, Laykold). Las canchas de alfombra son rollos de superficie sintética texturizada sobre una base firme, y juegan rápido y bajo. Algunos clubes usan arcilla artificial (césped sintético relleno de arena) bajo techo, que es más lenta y blanda. El aire interior está quieto y algo más seco, así que la pelota viaja un poco más rápido que en la misma cancha al aire libre.',
    playingStyle: 'Aprovecha las condiciones perfectas: apunta más cerca de las líneas, aplana el saque y haz más saque y volea que al aire libre. Sin viento puedes confiar en tu lanzamiento. La altura del techo importa para el globo y el smash; mira dónde están las luces antes de levantar una pelota alta. El sonido es más fuerte, así que usa esa respuesta acústica para juzgar qué tan limpio estás golpeando.',
    footwear: 'Zapatillas de cancha dura para toda superficie con suela que no marque (exigida en casi todos los pabellones). Para alfombra, usa una suela lisa o ligeramente texturizada; la espiga agarra demasiado y puede torcer un tobillo. Limpia las suelas antes de entrar para que el polvo no vuelva la cancha resbaladiza.',
    bodyNote: 'Las canchas duras cubiertas comparten el problema de impacto de la cancha dura, y la alfombra añade un agarre pegajoso que aumenta el riesgo de torceduras de tobillo y rodilla. El aire cálido interior te deshidrata más rápido de lo que esperas porque el sudor se evapora enseguida, así que bebe en cada cambio de lado.',
  },
]
