import type { Drill } from './types'

// Half-court coordinates for patterns: x runs from -5.5 (left doubles line)
// to 5.5, z runs from 0 (baseline) to 11.9 (net). Singles lines sit at
// x = ±4.1, the service line at z = 5.5, the service T at [0, 5.5].

export const DRILLS: Drill[] = [
  // ---------------------------------------------------------------- footwork
  {
    id: 'ready-position-and-split-step',
    name: 'Ready position and split step',
    section: 'footwork',
    level: 'beginner',
    goal: 'Groove the small hop that gets you off the mark early, so your first step to every ball is quick and balanced.',
    equipment: 'Two cones or ball tubes, a partner or coach who can call directions',
    setup: 'Stand on the centre mark about half a metre behind the baseline. Place a cone one metre to each side of you.',
    steps: [
      'Take your ready position: feet a little wider than your shoulders, knees soft, weight on the balls of your feet, racquet head up in front of you.',
      'Your partner mimics a swing. As their arm comes forward, hop a few centimetres off the ground and land with your feet slightly wider than before.',
      'Land as they would make contact, then push off the outside foot toward the cone your partner points at.',
      'Take one big first step, shadow a stroke at the cone, then shuffle back to the centre mark.',
      'Reset to ready position and wait for the next cue. Do not hop until you see the swing start.',
      'After ten reps, have your partner add fakes so you learn to hold the hop until the real cue.',
    ],
    reps: '3 sets of 10 splits, 30 seconds rest between sets',
    coachingCues: [
      'Small hop, wide landing. You are unweighting, not jumping.',
      'Land on the balls of both feet with knees bent, never on your heels.',
      'Time the landing to the opponent’s contact, not the bounce.',
      'Push off the foot furthest from the ball. Your first step should be explosive.',
    ],
    pattern: {
      points: [
        [0, 0.5],
        [-1, 0.5],
        [0, 0.5],
        [1, 0.5],
        [0, 0.5],
      ],
      cones: [
        [-1, 0.5],
        [1, 0.5],
      ],
    },
    studio: 'split-step',
  },
  {
    id: 'side-shuffle-recovery',
    name: 'Side shuffle recovery',
    section: 'footwork',
    level: 'beginner',
    goal: 'Learn to recover toward the centre while facing the net, so you can change direction the moment the next ball is struck.',
    equipment: 'Three cones',
    setup: 'Place one cone on the centre mark and one cone 3.5 metres to each side, all a metre behind the baseline.',
    steps: [
      'Start at the centre cone in ready position, chest facing the net.',
      'Shuffle to the left cone. Lead with the left foot, and never let your feet cross or click together.',
      'Touch the cone with your racquet, shadow a backhand, then shuffle back to the centre.',
      'Do a small split step at the centre, then shuffle to the right cone and shadow a forehand.',
      'Shuffle back to the centre again and split. That is one round trip.',
      'Keep your hips low the whole time. If you bob up and down you are losing time.',
    ],
    reps: '6 round trips, rest 45 seconds, repeat 3 times',
    coachingCues: [
      'Stay low and wide. Imagine sliding under a bar set at shoulder height.',
      'Feet never cross. Push with the trailing leg, reach with the leading leg.',
      'Eyes stay on the imaginary opponent, not on the cones.',
      'Finish each recovery with a split step, not a dead stop.',
    ],
    pattern: {
      points: [
        [0, 0.8],
        [-3.5, 0.8],
        [0, 0.8],
        [3.5, 0.8],
        [0, 0.8],
      ],
      cones: [
        [-3.5, 0.8],
        [0, 0.8],
        [3.5, 0.8],
      ],
    },
    studio: 'shuffle',
  },
  {
    id: 'crossover-step',
    name: 'Crossover step',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Cover wide balls fast with a crossover, then use the same step to recover when you have a long way back to the centre.',
    equipment: 'Two cones',
    setup: 'Cones on each singles sideline, one metre behind the baseline. Start on the centre mark in ready position.',
    steps: [
      'Split step, then turn your hips and cross your right foot over your left to run toward the left cone.',
      'Take two or three running strides, plant your outside foot beside the cone and shadow a wide backhand.',
      'Recover with a crossover: push off the outside leg, swing the far leg across your body, then finish the last two metres with shuffles.',
      'Split at the centre and repeat to the right cone with a wide forehand.',
      'Once the rhythm is there, have a partner point left or right at random.',
      'Add a ball: the partner hand-feeds wide and you hit off the outside leg before recovering.',
    ],
    reps: '8 wide balls per side, 2 sets, 60 seconds rest between sets',
    coachingCues: [
      'Crossover for distance, shuffle for the last steps. Do not shuffle five metres.',
      'Turn the hips first, then the feet follow.',
      'Plant the outside foot strong so you can push straight back toward the centre.',
      'Keep the racquet head up during the run, you need it ready at the end.',
    ],
    pattern: {
      points: [
        [0, 0.8],
        [-4.5, 0.8],
        [0, 0.8],
        [4.5, 0.8],
        [0, 0.8],
      ],
      cones: [
        [-4.5, 0.8],
        [4.5, 0.8],
      ],
    },
    studio: 'crossover',
  },
  {
    id: 'spider-drill',
    name: 'Spider drill',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Build the multi-directional speed and stopping strength tennis actually needs, and get a repeatable time to measure yourself against.',
    equipment: 'Five tennis balls, a racquet laid on the centre mark, a stopwatch',
    setup: 'Place a ball at each of five spots: both baseline and singles-line corners, both corners where the singles lines meet the service line, and the service T. Lay your racquet flat on the centre mark as the home base.',
    steps: [
      'Start at the centre mark in ready position. Your partner starts the clock on your first movement.',
      'Sprint to the left baseline corner, pick up the ball, run back and place it on the racquet.',
      'Run to the left service-line corner, collect the ball and bring it home.',
      'Run to the service T and back, then the right service-line corner and back.',
      'Finish with the right baseline corner. The clock stops when the fifth ball lands on the racquet.',
      'Rest fully, then reverse the order so you start on the right.',
      'Record every time. Good club players run it around 17 to 20 seconds, strong juniors and college players under 16.',
    ],
    reps: '4 to 6 timed runs with 90 seconds rest between them',
    coachingCues: [
      'Decelerate with small steps and a low hip, do not slam into a straight leg.',
      'Bend from the knees to pick up the ball, not just the back.',
      'Face the net for the short lateral distances, turn and run for the long ones.',
      'Placing the ball, not throwing it, is part of the test. Control under fatigue.',
    ],
    pattern: {
      points: [
        [0, 0],
        [-4.1, 0],
        [0, 0],
        [-4.1, 5.5],
        [0, 0],
        [0, 5.5],
        [0, 0],
        [4.1, 5.5],
        [0, 0],
        [4.1, 0],
        [0, 0],
      ],
      cones: [
        [-4.1, 0],
        [-4.1, 5.5],
        [0, 5.5],
        [4.1, 5.5],
        [4.1, 0],
      ],
    },
  },
  {
    id: 'figure-eight-baseline',
    name: 'Figure eight on the baseline',
    section: 'footwork',
    level: 'beginner',
    goal: 'Practise continuous change of direction while keeping the body facing the net, the way you do during a long baseline exchange.',
    equipment: 'Two cones',
    setup: 'Cones 2.5 metres either side of the centre mark, a metre and a half behind the baseline.',
    steps: [
      'Start between the cones facing the net.',
      'Shuffle left and loop around the left cone: forward of it, around the outside, then behind it.',
      'Cross the middle and loop around the right cone the opposite way, so your path draws a figure eight.',
      'Stay square to the net the entire time. Use shuffles on the sides and short adjusting steps on the curves.',
      'Add a shadow forehand every time you pass the right cone and a shadow backhand at the left cone.',
      'After 30 seconds, switch to a version where you run forwards and backwards around the cones.',
    ],
    reps: '30 seconds on, 30 seconds off, 6 rounds',
    coachingCues: [
      'Small steps around the cone, big steps between them.',
      'Head level, no bouncing. Your eyes should stay steady as if watching a ball.',
      'Lead with the hip, not the shoulder, when you change direction.',
    ],
    pattern: {
      points: [
        [0, 1.5],
        [-2.5, 2.5],
        [-3.5, 1.5],
        [-2.5, 0.5],
        [0, 1.5],
        [2.5, 2.5],
        [3.5, 1.5],
        [2.5, 0.5],
      ],
      loop: true,
      cones: [
        [-2.5, 1.5],
        [2.5, 1.5],
      ],
    },
  },
  {
    id: 'alley-hops',
    name: 'Alley hops',
    section: 'footwork',
    level: 'beginner',
    goal: 'Develop quick, light feet and ankle stiffness so you can adjust position with tiny hops before contact.',
    equipment: 'None, just the doubles alley',
    setup: 'Stand in the doubles alley beside the baseline, facing the net, with both feet just outside the singles sideline.',
    steps: [
      'Hop sideways over the singles line with both feet together, land softly, and hop straight back.',
      'Keep hopping across the alley for 20 seconds, moving very slightly forward with each hop.',
      'Switch to single-leg hops: left foot only for 15 seconds, then right foot only.',
      'Next round, hop over the line and touch the ground with your racquet head after every landing.',
      'Finish with quick feet: tiny alternating steps over the line as fast as possible for 15 seconds.',
    ],
    reps: '4 rounds of the full sequence with 40 seconds rest',
    coachingCues: [
      'Land quietly. Loud feet mean stiff landings.',
      'Stay on the balls of your feet with the heels barely kissing the ground.',
      'Arms relaxed and racquet out in front, as if a ball could arrive any time.',
    ],
    pattern: {
      points: [
        [4.1, 0.5],
        [5.5, 1],
        [4.1, 1.5],
        [5.5, 2],
        [4.1, 2.5],
        [5.5, 3],
      ],
      cones: [
        [4.1, 0.5],
        [5.5, 3],
      ],
    },
  },
  {
    id: 'serve-plus-one-recovery',
    name: 'Serve plus one recovery',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Land from the serve balanced and immediately ready for the return, then hit a strong first groundstroke and recover.',
    equipment: 'Basket of balls, one cone, a partner to feed',
    setup: 'Serve from the deuce court about a metre right of the centre mark. Place a cone three metres to the right of the centre mark, a metre behind the baseline, where a typical return lands.',
    steps: [
      'Serve into the deuce box. Land on your front foot inside the baseline, with the back leg kicking back for balance.',
      'Take one recovery step back behind the baseline and split step as the returner would make contact.',
      'Your partner hand-feeds or racquet-feeds a ball toward the cone the moment you land.',
      'Move to the ball with a crossover, set up in a semi-open stance and hit a forehand cross-court.',
      'Recover with shuffles to just right of the centre mark and split again.',
      'Alternate: every second serve, the partner feeds to the backhand instead.',
    ],
    reps: '10 serve-plus-one sequences, 3 sets, 90 seconds rest between sets',
    coachingCues: [
      'Balance on landing is the whole point of the serve follow-through. Stick it.',
      'Split before the return, not after. Watch the returner’s racquet.',
      'Hit the plus-one big to a big target. Do not aim for lines off the first ball.',
      'Recover toward the side you hit to, not the exact centre.',
    ],
    pattern: {
      points: [
        [1, 0],
        [0.8, 0.6],
        [0.8, 0.8],
        [3, 1],
        [0.5, 0.8],
      ],
      cones: [
        [3, 1],
      ],
    },
  },
  {
    id: 'approach-and-split',
    name: 'Approach and split',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Move forward through an approach shot without stopping, then split step before the volley so you are never caught mid-stride at the net.',
    equipment: 'Basket of balls, two cones, a feeder',
    setup: 'One cone around the service line just right of centre where the short ball lands, another two metres inside the service line where you want to volley from. Start on the centre mark.',
    steps: [
      'Feeder plays a short ball to the first cone. Run forward and hit a slice or drive approach down the line off a carioca or running step.',
      'Do not stop after contact. Keep moving forward in a straight line toward the second cone.',
      'Feeder starts the next swing as you reach the cone. Split step and land wide.',
      'Move diagonally to the volley, punch it, and take one more small step forward.',
      'Shuffle back to the middle of the service boxes and finish in ready position.',
      'Repeat approaching on the backhand side, then mix them up at random.',
    ],
    reps: '8 sequences per side, 2 sets, 60 seconds rest between sets',
    coachingCues: [
      'Approach then keep going. The shot is part of the run, not a stop.',
      'Split when the opponent’s racquet moves, wherever you are on the court.',
      'Land the split with your weight forward so you can attack the volley.',
      'Follow the direction of your approach: down the line means shift to that side.',
    ],
    pattern: {
      points: [
        [0, 0.5],
        [1.5, 4],
        [1, 8],
        [0.5, 9.5],
        [0, 7],
      ],
      cones: [
        [1.5, 4],
        [1, 8],
      ],
    },
  },
  {
    id: 'drop-step-for-the-lob',
    name: 'Drop step for the lob',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Turn and cover a lob with a drop step and crossovers rather than backpedalling, so you reach the overhead balanced and behind the ball.',
    equipment: 'Basket of balls, one cone, a feeder who can toss lobs',
    setup: 'Start about three metres from the net, slightly right of centre, in a volley ready position. Place a cone around the service line where a decent lob would bounce.',
    steps: [
      'Feeder tosses a lob over your right shoulder.',
      'Drop step: immediately step back with your right foot and turn your shoulders sideways, pointing at the ball with your non-dominant hand.',
      'Use crossover steps to move back under the ball. Never run backwards facing the net.',
      'Set up with your weight on the back foot, then shadow an overhead as you drive up and forward.',
      'Land and shuffle straight back to the net position.',
      'Progress to hitting real overheads, then to lobs over the left shoulder where you will turn the other way.',
    ],
    reps: '10 lobs per shoulder, 2 sets, 60 seconds rest between sets',
    coachingCues: [
      'Drop step first. The step back and the turn happen together.',
      'Point at the ball to keep the shoulders sideways and the tracking eye steady.',
      'Get behind the ball, not under it. You want to move forward into contact.',
      'If the lob is too deep, let it bounce and hit a bounce smash.',
    ],
    pattern: {
      points: [
        [0.5, 9],
        [1, 7.5],
        [1.5, 6],
        [2, 4.5],
        [0.5, 9],
      ],
      cones: [
        [2, 4.5],
      ],
    },
  },
  {
    id: 'mirror-drill-with-partner',
    name: 'Mirror drill with partner',
    section: 'footwork',
    level: 'beginner',
    goal: 'React to an unpredictable cue and move in every direction with proper footwork, in a game that never gets boring.',
    equipment: 'Four cones, a partner',
    setup: 'Mark a box five metres wide and about two and a half metres deep behind the baseline. Partners face each other across the net or side by side, one is the leader.',
    steps: [
      'Both partners start in ready position. The leader moves anywhere inside the box using shuffles, crossovers and small steps.',
      'The follower mirrors every move as closely as possible, staying square to the leader.',
      'Leader changes direction at least every two seconds, mixing lateral, forward and backward moves.',
      'After 20 seconds, freeze. Note how far apart you have drifted, then swap roles.',
      'Round three: the leader adds shadow strokes and the follower must copy the stroke as well as the move.',
      'Round four: the leader tries to lose the follower with fakes, testing the follower’s split step.',
    ],
    reps: '20 seconds work, 20 seconds rest, 8 rounds alternating leader',
    coachingCues: [
      'Follower: watch the hips, not the feet. Hips tell you where someone is going.',
      'Stay low between moves. Standing up tall between moves is what makes you late.',
      'Leader: be honest and use real tennis footwork, not dance steps.',
    ],
    pattern: {
      points: [
        [0, 1],
        [-2, 1],
        [-1, 2.5],
        [1.5, 2],
        [2, 0.5],
        [0, 1],
      ],
      cones: [
        [-2.5, 0.5],
        [2.5, 0.5],
        [-2.5, 3],
        [2.5, 3],
      ],
    },
  },
  {
    id: 'cone-triangle-hitting',
    name: 'Cone triangle hitting',
    section: 'footwork',
    level: 'intermediate',
    goal: 'Combine movement to a wide forehand, a wide backhand and a short ball with a full recovery between each, exactly like a real point.',
    equipment: 'Three cones, basket of balls, a feeder',
    setup: 'Cones three metres left and right of the centre mark along the baseline, and one cone in the middle about three metres inside the baseline. Start on the centre mark.',
    steps: [
      'Feeder plays a ball to the left cone. Move with crossovers, hit a backhand cross-court and shuffle back to the centre.',
      'Split step. The next feed goes to the right cone: forehand cross-court, recover.',
      'Split. The third feed is short to the middle cone. Move forward, hit a forehand down the line and back up to the baseline.',
      'That triangle is one rep. The feeder should feed as you arrive at the centre, not before.',
      'Every third triangle, reverse the order so you do not start guessing.',
      'For an advanced version, the feeder calls out which cone a beat before feeding.',
    ],
    reps: '6 triangles per set, 3 sets, 90 seconds rest between sets',
    coachingCues: [
      'Recover before the next ball is fed. If you are still moving, you are late.',
      'Hit off the outside leg on the wide balls, then push back off that same leg.',
      'On the short ball, move through it. Do not run, stop and then swing.',
      'Keep the same swing shape when tired. Footwork drills are about hitting well while moving, not just moving.',
    ],
    pattern: {
      points: [
        [0, 0.8],
        [-3, 1],
        [0, 0.8],
        [3, 1],
        [0, 0.8],
        [0, 3],
        [0, 0.8],
      ],
      cones: [
        [-3, 1],
        [3, 1],
        [0, 3],
      ],
    },
  },

  // ------------------------------------------------------------ coordination
  {
    id: 'ball-bounce-and-catch',
    name: 'Ball bounce and catch',
    section: 'coordination',
    level: 'beginner',
    goal: 'Teach young players to track a bouncing ball and judge where it will be, before a racquet is involved.',
    equipment: 'One red or orange low-compression ball per child, chalk or a flat marker',
    setup: 'Each child stands in their own space with a ball, on a smooth surface where the ball bounces true.',
    steps: [
      'Drop the ball from waist height and catch it with both hands after one bounce. Ten times.',
      'Drop and catch with one hand only, then the other hand.',
      'Bounce the ball down with one hand and catch it after the bounce with the same hand. Ten in a row.',
      'Throw the ball up gently, let it bounce once, and catch it. Move your feet so it bounces in front of you.',
      'Partner version: one throws a slow underarm ball, the other lets it bounce once and catches it, then rolls it back.',
      'Game: how many bounce-and-catches can you do while walking to the net and back?',
    ],
    reps: '10 of each variation, then 5 minutes of games',
    coachingCues: [
      'Watch the ball all the way into your hands.',
      'Move your feet so the ball comes to you, do not reach.',
      'Catch with soft hands, as if catching an egg.',
    ],
  },
  {
    id: 'racquet-balance-walk',
    name: 'Racquet balance walk',
    section: 'coordination',
    level: 'beginner',
    goal: 'Get comfortable feeling the racquet head and controlling it with small adjustments, so the racquet becomes an extension of the hand.',
    equipment: 'A junior racquet and a ball per child, a few cones',
    setup: 'Set up a simple course with cones from the baseline to the service line.',
    steps: [
      'Hold the racquet in front of you with the face flat, like a tray, and balance the ball on the strings.',
      'Walk slowly from the baseline to the service line without the ball falling. Restart if it drops.',
      'Walk back weaving between the cones.',
      'Next round: flip the racquet so you balance the ball on the other face of the strings, then switch hands.',
      'Try walking with the racquet face held out to the side, as if getting ready to hit a forehand.',
      'Relay race: teams of two or three, pass the ball from racquet to racquet without using hands.',
    ],
    reps: '3 trips each variation, then a 5-minute relay',
    coachingCues: [
      'Soft grip. Squeezing hard makes the racquet shake.',
      'Watch the ball, not your feet. Your feet will figure it out.',
      'Tiny adjustments, keep the racquet face level with the ground.',
    ],
  },
  {
    id: 'self-rally-ups-and-downs',
    name: 'Self rally: ups and downs',
    section: 'coordination',
    level: 'beginner',
    goal: 'Learn to make the centre of the strings meet the ball repeatedly, with the racquet doing the work and the eyes leading.',
    equipment: 'A racquet and a red or orange ball per child',
    setup: 'Each child in their own space, at least two metres from anyone else.',
    steps: [
      'Downs: bounce the ball on the ground with the racquet, like dribbling in basketball. Count how many in a row.',
      'Ups: tap the ball straight up off the strings, about head height, and catch it. Then try two ups, then three.',
      'Keep going for as many ups as possible. Bend your knees and stay under the ball.',
      'Alternate one up, then flip the racquet and hit the next up with the other face.',
      'Combine: one up, let it bounce, one down, back to an up.',
      'Challenge: ups while walking, then ups while sitting down and standing up.',
    ],
    reps: '2 minutes of each, aim to beat your best streak',
    coachingCues: [
      'Watch the ball meet the strings every time.',
      'Small taps. Big swings make the ball go wild.',
      'Move your feet to stay under the ball rather than reaching for it.',
      'Racquet face flat toward the sky for ups, toward the ground for downs.',
    ],
  },
  {
    id: 'toss-and-clap',
    name: 'Toss and clap',
    section: 'coordination',
    level: 'beginner',
    goal: 'Improve ball tracking, timing and rhythm, and build the toss control the serve will need later.',
    equipment: 'One ball per child',
    setup: 'Each child standing with space around them, feet shoulder-width apart.',
    steps: [
      'Toss the ball straight up to just above head height and catch it with the same hand. Ten times, no chasing it.',
      'Toss, clap once while the ball is in the air, catch.',
      'Toss, clap twice, catch. Then three claps if you can.',
      'Toss, turn your hips to the side, and catch with your palm facing the sky, like a serve toss.',
      'Toss with the non-dominant hand and catch with the dominant hand.',
      'Partner version: toss to yourself, clap, and your partner counts how many clean catches in a row.',
    ],
    reps: '10 of each variation',
    coachingCues: [
      'Lift the ball from the palm and fingers, not a flick of the wrist.',
      'Toss to the same spot every time so you never have to move your feet.',
      'Eyes on the ball at the top of the toss, that is when it is easiest to see.',
    ],
  },
  {
    id: 'two-ball-juggle-drop',
    name: 'Two-ball juggle drop',
    section: 'coordination',
    level: 'beginner',
    goal: 'Challenge peripheral vision, timing and two-hand independence with a game that feels like juggling but stays achievable.',
    equipment: 'Two balls per child, different colours if possible',
    setup: 'Each child with a ball in each hand, standing still.',
    steps: [
      'Toss the right-hand ball up, then quickly pass the left-hand ball to the right hand and catch the falling ball with the left. Slowly.',
      'Repeat starting with the left hand.',
      'Two-ball drop: hold both balls at shoulder height, drop them at the same time and catch both after one bounce.',
      'Drop both, clap, then catch both after the bounce.',
      'Drop both and catch them crossed: right hand catches the left ball and vice versa.',
      'Partner throws you two balls at once, one low bounce and one high. Catch both.',
    ],
    reps: '10 attempts per variation, count successes',
    coachingCues: [
      'Look between the two balls, not at one of them.',
      'Toss low. A toss to eye height is plenty.',
      'Relax the hands and let the ball land in them.',
    ],
  },
  {
    id: 'reaction-ball-drop',
    name: 'Reaction ball drop',
    section: 'coordination',
    level: 'beginner',
    goal: 'Sharpen reaction time and the first explosive step, the two things that separate reaching a ball from watching it go by.',
    equipment: 'A ball, a partner, optionally a six-sided reaction ball',
    setup: 'Partner stands two metres in front of you holding a ball out at shoulder height. You are in ready position.',
    steps: [
      'Partner drops the ball without warning. Sprint forward and catch it after one bounce, before the second.',
      'Move back to the start. Partner drops again, this time from a lower height so you have less time.',
      'Partner holds a ball in each hand and drops one at random. React to the correct side.',
      'You start facing away. Partner says go as they drop; turn and catch after one bounce.',
      'Partner drops the ball two metres to your left or right so you must move laterally first.',
      'Replace the tennis ball with a reaction ball for an unpredictable bounce.',
    ],
    reps: '10 drops per variation, 3 variations per session',
    coachingCues: [
      'Watch the hand, not the ball. The hand moves first.',
      'First step big and low, then adjust with small steps.',
      'Stay on your toes in ready position, heels off the ground.',
    ],
  },
  {
    id: 'ladder-basics',
    name: 'Ladder basics',
    section: 'coordination',
    level: 'beginner',
    goal: 'Build rhythm, foot speed and the ability to place your feet precisely without looking at them.',
    equipment: 'Agility ladder, or chalk lines about 45 centimetres apart',
    setup: 'Lay the ladder along the baseline or perpendicular to the net. Start at one end in ready position.',
    steps: [
      'One foot in each square: walk it first, then jog, then run. Land on the balls of the feet.',
      'Two feet in each square: right in, left in, move to the next square. Quick, light steps.',
      'In-in-out-out: both feet into a square one after the other, then both feet out to the side of the next square, and repeat.',
      'Icky shuffle: right foot into the square, left foot into the square, right foot out to the right side. Then left in, right in, left out to the left. Continue alternating.',
      'Lateral two-in: face sideways to the ladder and step both feet into each square moving down the ladder.',
      'Finish each run with a split step and shadow stroke at the end of the ladder.',
    ],
    reps: '3 runs of each pattern, walk back as rest',
    coachingCues: [
      'Rhythm before speed. Say the pattern out loud as you go.',
      'Eyes up. Trust your feet and look toward the net.',
      'Arms move too, elbows bent like a sprinter.',
      'Stay low, do not high-knee it.',
    ],
  },

  // ----------------------------------------------------------------- fitness
  {
    id: 'lateral-lunge-series',
    name: 'Lateral lunge series',
    section: 'fitness',
    level: 'intermediate',
    goal: 'Strengthen the hips and legs in the sideways positions tennis demands, so wide balls and hard stops do not cost you your knees or ankles.',
    equipment: 'Bodyweight to start, a light dumbbell or medicine ball later',
    setup: 'A flat surface with two metres of space to each side. Warm up with two minutes of light skipping or jogging first.',
    steps: [
      'Lateral lunge: step wide to the right, sit the hips back and down over the right foot, left leg straight. Push back to standing. Eight per side.',
      'Lateral lunge with reach: same lunge, but reach both hands toward the outside foot as if picking up a low ball.',
      'Cossack squat: from a wide stance, shift all weight onto one leg and sink as low as you can, other heel on the ground, toes up. Six per side.',
      'Curtsy lunge: step the right foot behind and across the left, bend both knees, return. Eight per side.',
      'Lateral bound and stick: hop sideways off one leg, land on the other and hold the landing for two seconds. Six per side.',
      'Finish with a 20-second lateral lunge hold each side.',
    ],
    reps: '2 to 3 rounds, 60 seconds rest between rounds, twice a week',
    coachingCues: [
      'Knee tracks over the middle of the foot, never rolling inward.',
      'Sit the hips back like you are loading for a wide forehand.',
      'Chest up, spine long. Do not fold forward.',
      'Stick every landing before you move again.',
    ],
  },
  {
    id: 'medicine-ball-rotational-throws',
    name: 'Medicine ball rotational throws',
    section: 'fitness',
    level: 'intermediate',
    goal: 'Train the legs, hips and trunk to produce and transfer rotational power in the same sequence as a groundstroke.',
    equipment: 'Medicine ball of 2 to 4 kilograms and a solid wall, or a partner',
    setup: 'Stand side-on to the wall about two metres away in a semi-open forehand stance.',
    steps: [
      'Forehand throw: hold the ball at hip height on your right side, load into the right leg, then rotate hips first, shoulders second, and throw the ball into the wall. Catch the rebound and repeat. Eight throws.',
      'Backhand throw: turn around and repeat from the other side, mimicking a two-handed backhand. Eight throws.',
      'Open-stance throw: feet parallel to the wall, load the outside leg fully and throw with pure rotation. Six per side.',
      'Step-and-throw: start a metre further back, step into a neutral stance and throw as you transfer weight. Six per side.',
      'Overhead slam: raise the ball above your head, extend up through the legs and slam it into the ground. Eight slams.',
      'Rest 90 seconds and repeat the whole set.',
    ],
    reps: '3 sets, 8 throws per pattern, twice a week on non-match days',
    coachingCues: [
      'Legs and hips start the throw. Arms are the last thing to move.',
      'Stay balanced after the release, just like a finish on a forehand.',
      'Throw hard but under control. If you lose your form, the ball is too heavy.',
      'Full recovery between sets. This is power work, not conditioning.',
    ],
  },
  {
    id: 'skipping-intervals',
    name: 'Skipping intervals',
    section: 'fitness',
    level: 'intermediate',
    goal: 'Develop quick, elastic feet and calf and ankle resilience with an activity that fits into any warm-up or conditioning session.',
    equipment: 'A skipping rope sized so the handles reach your armpits when you stand on the middle',
    setup: 'A flat surface, ideally the court or a sprung floor rather than concrete.',
    steps: [
      'Two minutes of easy two-footed skipping to warm up.',
      '30 seconds fast two-foot skipping, 30 seconds slow. Four rounds.',
      '30 seconds alternating single-leg skips, 30 seconds slow. Four rounds.',
      '30 seconds side-to-side skips: hop a few centimetres left and right over an imaginary line. 30 seconds slow. Four rounds.',
      '20 seconds double-unders if you can, otherwise maximum speed. 40 seconds slow. Three rounds.',
      'Finish with a minute of easy skipping and some calf stretches.',
    ],
    reps: '15 to 18 minutes total, 2 to 3 times a week',
    coachingCues: [
      'Jump just high enough for the rope. Small hops, quiet landings.',
      'Turn the rope from the wrists, elbows stay close to the body.',
      'Land on the balls of the feet with heels barely touching.',
      'Keep your eyes forward and posture tall.',
    ],
  },
  {
    id: 'shoulder-care-band-work',
    name: 'Shoulder care band work',
    section: 'fitness',
    level: 'intermediate',
    goal: 'Keep the rotator cuff and shoulder blade muscles strong and balanced, so thousands of serves do not turn into a sore shoulder.',
    equipment: 'A light resistance band, a door anchor or fence post',
    setup: 'Anchor the band at elbow height. Do this before serving practice or as a stand-alone routine.',
    steps: [
      'External rotation: elbow tucked at your side, bent to 90 degrees, rotate the forearm outward against the band. 15 slow reps per arm.',
      'Internal rotation: face the other way and rotate the forearm inward. 15 reps per arm.',
      'External rotation at 90 degrees: elbow raised to shoulder height, rotate the hand up and back into the serve trophy position. 12 reps per arm.',
      'Band pull-aparts: hold the band with both hands at shoulder height, pull it apart until the arms are wide, squeezing the shoulder blades. 15 reps.',
      'Face pulls: pull the band toward your face with elbows high, finishing with thumbs beside your ears. 15 reps.',
      'Scapular Ys: anchor low, raise both arms up and out in a Y shape, thumbs up. 12 reps.',
      'Add wrist extensor work: palm-down wrist curls with the band or a light dumbbell, 15 reps. This is your tennis elbow insurance.',
    ],
    reps: '2 rounds, 3 to 4 times a week, more during heavy serving weeks',
    coachingCues: [
      'Slow on the way out, slower on the way back. Two seconds each way.',
      'Light band. If you are straining, the band is too heavy for this job.',
      'Shoulder blades down and back before every rep.',
      'No shrugging. The neck stays relaxed.',
    ],
  },
  {
    id: 'tennis-specific-interval-runs',
    name: 'Tennis-specific interval runs',
    section: 'fitness',
    level: 'advanced',
    goal: 'Condition your body to repeat short, intense efforts with brief rests, matching the real rhythm of points and the pauses between them.',
    equipment: 'Four cones, a timer with audible beeps or an interval app',
    setup: 'Cones on the centre mark and each singles sideline along the baseline, plus one at the service T. A point averages 5 to 8 seconds, and you get about 20 seconds between points, so the intervals follow that shape.',
    steps: [
      'Work 20 seconds: sprint from the centre to the left sideline cone and back, then to the right cone and back, shuffling the last two metres each time. Keep going until the beep.',
      'Rest 20 seconds: walk slowly back to the centre and breathe, like you would between points.',
      'Repeat for 8 intervals. That is roughly one game.',
      'Take a 90-second changeover rest, sitting or standing still.',
      'Second game: alternate the pattern. Sprint to the service T and back, then lateral to a sideline and back.',
      'Third game: add shadow strokes at each cone so your arms work too.',
      'Play 3 to 5 games in total depending on your fitness. Log how many cone touches you managed in the last game compared to the first.',
    ],
    reps: '3 to 5 games of 8 intervals, once or twice a week in the off-season',
    coachingCues: [
      'Every rep at match intensity. If you jog, you are training to jog.',
      'Deceleration is the work. Low hips and small steps into every turn.',
      'Use the rest exactly as you would between points: slow walk, deep breath, refocus.',
      'When quality drops sharply, stop the session. Sloppy movement under fatigue teaches sloppy movement.',
    ],
  },
]
