import type { Grip } from './types'

// Bevel numbering is for a right-hander holding the racquet on edge with
// bevel 1 on top and counting clockwise as seen from the butt cap. A
// left-hander mirrors every number (bevel 2 becomes bevel 8, 3 becomes 7,
// and so on).
export const GRIPS: Grip[] = [
  {
    id: 'continental',
    name: 'Continental',
    indexKnuckle: 2,
    heelPad: 2,
    strokes: ['serve', 'slice', 'forehand-volley', 'backhand-volley', 'smash', 'back-smash', 'drop-shot', 'tweener'],
    feel: 'The hammer grip. The racquet face sits slightly open, the wrist is free to snap, and the same grip covers both sides of your body so you never need to change at the net.',
    howToFind: 'Hold the racquet on edge as if you were going to hammer a nail with the frame. Your index base knuckle and heel pad both rest on bevel 2, the small bevel between the top and the right side. Another check: the V between thumb and index finger points at the left edge of the top bevel. Shaking hands with the handle gets you close.',
    pros: [
      'Lets the wrist pronate on the serve, which is where pace and spin come from',
      'Opens the face naturally for slice, volleys and drop shots',
      'One grip for both volleys, so there is nothing to change in a fast exchange',
      'The only grip that makes a proper smash and back-smash possible',
    ],
    cons: [
      'Weak for topspin groundstrokes: the face is open, so high balls are hard to control',
      'Forehands hit with it tend to float or sail long against heavy pace',
      'Feels awkward for the first few weeks because the racquet face is not where beginners expect it',
    ],
    usedBy: ['Every professional on serve and volley', 'Roger Federer (volleys, slice)', 'John McEnroe (forehand and everything else)', 'Ash Barty (slice backhand)'],
  },
  {
    id: 'eastern-forehand',
    name: 'Eastern forehand',
    indexKnuckle: 3,
    heelPad: 3,
    strokes: ['forehand', 'swing-volley', 'return', 'drop-shot'],
    feel: 'A shake-hands grip. Palm sits behind the handle, so contact feels solid and the racquet face is close to vertical. Easy to hit flat, easy to add a little topspin, and quick to change to continental.',
    howToFind: 'Lay the racquet flat on a table with the strings facing the ceiling, then pick it up by the handle as if shaking hands with it. The index base knuckle and heel pad land on bevel 3, the right side of the handle. Your palm is now on the same plane as the strings.',
    pros: [
      'Most natural grip for a beginner: the face is square to the ball at contact',
      'Comfortable on low and medium bounces and fast courts',
      'Easiest to flatten out for a putaway or a swinging volley',
      'One bevel away from continental, so grip changes to the net are quick',
    ],
    cons: [
      'Struggles with high, heavy topspin balls above shoulder height',
      'Less natural topspin than semi-western, so margin over the net is thinner',
      'Wrist can get lazy and open the face late in a long rally',
    ],
    usedBy: ['Roger Federer', 'Juan Martín del Potro', 'Pete Sampras', 'Steffi Graf', 'Grigor Dimitrov (between eastern and semi-western)'],
  },
  {
    id: 'semi-western',
    name: 'Semi-western forehand',
    indexKnuckle: 4,
    heelPad: 4,
    strokes: ['forehand', 'return', 'swing-volley'],
    feel: 'The modern default. The hand is partly under the handle, so the face is slightly closed and the low-to-high swing brushes up the back of the ball. Heavy topspin with plenty of pace, and a good contact point around waist to chest height, slightly in front of the body.',
    howToFind: 'Start from eastern forehand (bevel 3) and rotate your hand one bevel clockwise, so the index base knuckle and heel pad sit on bevel 4, the bottom right bevel. Or place the racquet face down on the ground and pick it up naturally: most people pick it up in a semi-western.',
    pros: [
      'Natural topspin gives you a high margin over the net and a ball that kicks up at the opponent',
      'Handles high bounces on clay and heavy topspin comfortably',
      'Still flexible enough to flatten a short ball',
      'The grip most coaches teach from the orange-ball stage onwards',
    ],
    cons: [
      'Low, skidding balls (grass, slice) need a deep knee bend',
      'Two bevels from continental, so volley grip changes need practice',
      'Tempts players to over-rotate the wrist and hit short with too much spin',
    ],
    usedBy: ['Novak Djokovic', 'Rafael Nadal', 'Carlos Alcaraz', 'Jannik Sinner', 'Iga Świątek', 'Aryna Sabalenka'],
  },
  {
    id: 'western',
    name: 'Western forehand',
    indexKnuckle: 5,
    heelPad: 5,
    strokes: ['forehand'],
    feel: 'Hand fully under the handle so the face is clearly closed. Contact point is further out in front and higher, and the swing comes up steeply, producing very heavy topspin and a bounce that jumps off the court.',
    howToFind: 'Rotate one more bevel past semi-western so that the index base knuckle and heel pad are on bevel 5, the bottom of the handle. The palm now faces upward and the strings face the ground when your arm hangs. Some coaches call this the frying-pan grip.',
    pros: [
      'Maximum topspin and net clearance',
      'Very comfortable on shoulder-high balls, so it thrives on slow, high-bouncing clay',
      'Easy to hit sharp angles because the closed face and spin pull the ball down quickly',
    ],
    cons: [
      'Low balls and slice are a real problem: you have to bend a long way and the face still wants to close',
      'Three bevels from continental, so switching to volley or slice is slow',
      'Hard to flatten out; the ball often lacks penetration on fast courts',
      'Heavy load on the wrist and elbow for young players who copy it before they are strong enough',
    ],
    usedBy: ['Jack Sock', 'Karen Khachanov', 'Kei Nishikori', 'Alberto Berasategui (famously extreme, hit both sides with one face)', 'Many clay-court juniors'],
  },
  {
    id: 'eastern-backhand',
    name: 'Eastern backhand',
    indexKnuckle: 1,
    heelPad: 1,
    strokes: ['backhand-one-handed', 'slice'],
    feel: 'The standard one-handed topspin backhand grip. Knuckles on top of the handle put the back of the hand behind the racquet at contact, which gives a firm, solid feel and a vertical face for topspin and drives.',
    howToFind: 'From continental, rotate the hand one bevel anticlockwise so that the index base knuckle and heel pad sit on bevel 1, the flat top of the handle. Your knuckles should face the net when you take the racquet back, and your thumb wraps diagonally around the back for support.',
    pros: [
      'Strong structure for the one-hander: the hand is behind the ball at contact',
      'Easy to hit through the ball with topspin or flat',
      'Only one bevel from continental, so slice and volley changes are fast',
    ],
    cons: [
      'Balls above the shoulder are difficult; the one-hander has to step in or slice',
      'Contact point must be well in front, so late preparation is punished',
      'Needs a stronger forearm than a two-hander, which takes juniors time to develop',
    ],
    usedBy: ['Roger Federer', 'Stan Wawrinka', 'Grigor Dimitrov', 'Stefanos Tsitsipas'],
  },
  {
    id: 'extreme-eastern-backhand',
    name: 'Extreme eastern backhand',
    indexKnuckle: 8,
    heelPad: 8,
    strokes: ['backhand-one-handed'],
    feel: 'A one-handed backhand with the hand rotated further so the face is more closed. The ball can be taken higher, and the swing path brushes up steeply for heavy topspin, at the cost of a less friendly slice and a narrower contact window.',
    howToFind: 'From eastern backhand (bevel 1), rotate one more bevel anticlockwise so the index base knuckle and heel pad sit on bevel 8, the small bevel between the top and the left side. The palm now sits partly on top of the handle and the strings face slightly down when you hold the racquet out to the side.',
    pros: [
      'Lets a one-hander deal with shoulder-high balls and heavy topspin on clay',
      'Produces very heavy topspin, which gives margin on passing shots',
      'The closed face naturally drives the ball up and over from low contact',
    ],
    cons: [
      'Two bevels from continental, so the change to slice or volley is slower',
      'Flat drives lose penetration and the ball can be short',
      'Timing is critical: a late hit goes long or into the net',
      'Wrist and forearm load is high, so build strength before adopting it',
    ],
    usedBy: ['Richard Gasquet', 'Dominic Thiem', 'Lorenzo Musetti', 'Justine Henin'],
  },
  {
    id: 'two-handed-backhand',
    name: 'Two-handed backhand',
    indexKnuckle: 2,
    heelPad: 2,
    strokes: ['backhand-two-handed', 'return'],
    feel: 'Two hands share the work: the bottom (dominant, right) hand in continental steers and stabilises, the top (left) hand in an eastern forehand does most of the hitting. It feels like a left-handed forehand with the right hand along for the ride.',
    howToFind: 'Right hand first: hold a continental grip (bevel 2) at the bottom of the handle, as for a volley. Then place the left hand above it, touching, in an eastern forehand for a left-hander: left index base knuckle and heel pad on bevel 7, which is the mirror image of bevel 3. Check that the left palm sits behind the handle, facing the net at contact. Some players use a semi-western left hand (bevel 6) for more topspin, and some rotate the right hand to eastern backhand (bevel 1) for a firmer wrist.',
    pros: [
      'Stable and powerful, especially for juniors and anyone without a strong forearm',
      'Handles high balls and heavy pace well: the two hands act as a lever',
      'The right hand is already in continental, so a switch to slice or volley only means letting go with the left',
      'Easy to disguise and to hit on the run or off a short backswing on the return',
    ],
    cons: [
      'Less reach than a one-hander, so wide balls need an extra step or a one-handed slice',
      'Low, short balls need deep bending because both hands limit how far you can drop the racquet',
      'Players can become dependent on it and neglect the one-handed slice',
    ],
    usedBy: ['Novak Djokovic', 'Rafael Nadal', 'Andre Agassi', 'Iga Świątek', 'Serena Williams', 'Coco Gauff'],
  },
]
