import type { PathStage } from './types'

// Eleven stages from never having held a racquet to a tournament-level
// all-court player. Ranges are a rough guide in hours on court.

export const PATH: PathStage[] = [
  {
    n: 0,
    title: 'First contact',
    range: '0–10 hours',
    who: 'You have never held a racquet, or you tried once years ago and remember nothing.',
    goals: [
      'Understand what the court, the lines and the net are for',
      'Hold the racquet with a grip that works for a basic forehand',
      'Make the middle of the strings meet the ball on purpose',
      'Know how a point is won and lost',
    ],
    items: [
      { label: 'Learn the court lines and what each one means', to: '/learn/courts' },
      { label: 'Find out which ball you should be using to start', to: '/learn/balls' },
      { label: 'Pick a racquet that suits a beginner', to: '/learn/racquets' },
      { label: 'Learn the eastern forehand grip and how to find it', to: '/learn/grips' },
      { label: 'Do the ball bounce and catch and ups and downs drills', to: '/learn/footwork' },
      { label: 'Watch the forehand in slow motion', to: '/studio/forehand' },
      { label: 'Learn how points are scored', to: '/learn/scoring' },
    ],
    milestone: 'Bounce the ball on the ground with the racquet 20 times in a row, then hit 5 self-fed forehands over the net into the court.',
  },
  {
    n: 1,
    title: 'Rally ready',
    range: '10–30 hours',
    who: 'You can hit a ball over the net but a rally of more than three balls feels like luck.',
    goals: [
      'Hit a forehand and a backhand with a repeatable swing shape',
      'Adopt a ready position and start to split step',
      'Move to the ball and stop before swinging',
      'Rally cooperatively over the net with a partner',
    ],
    items: [
      { label: 'Study the two-handed backhand', to: '/studio/backhand-two-handed' },
      { label: 'Or, if it suits you better, the one-handed backhand', to: '/studio/backhand-one-handed' },
      { label: 'Learn the ready position and split step', to: '/studio/split-step' },
      { label: 'Practise side shuffle recovery and the figure eight', to: '/learn/footwork' },
      { label: 'Read why footwork decides everything', to: '/learn/footwork' },
      { label: 'Learn the basic rules: lets, faults and who serves', to: '/learn/rules' },
    ],
    milestone: '20-ball cooperative rally cross-court with a partner from the service line, using forehands and backhands.',
  },
  {
    n: 2,
    title: 'Court smart',
    range: '30–60 hours',
    who: 'You can rally short and you want to play actual points, serve included.',
    goals: [
      'Serve with a continental grip and a consistent toss',
      'Rally from the baseline with topspin and depth',
      'Keep score correctly through a full game and set',
      'Recover toward the centre after every ball',
    ],
    items: [
      { label: 'Learn the serve from the toss up', to: '/studio/serve' },
      { label: 'Find the continental grip', to: '/learn/grips' },
      { label: 'Run the ready position, shuffle and crossover drills', to: '/studio/shuffle' },
      { label: 'Learn scoring, tiebreaks and changeovers', to: '/learn/scoring' },
      { label: 'Read first tactics: consistency and depth', to: '/learn/tactics' },
      { label: 'Start a warm-up and cool-down habit', to: '/learn/fitness' },
    ],
    milestone: 'Serve 6 of 10 serves into the correct box from the baseline, and play a full set with correct scoring.',
  },
  {
    n: 3,
    title: 'Point builder',
    range: '60–120 hours',
    who: 'You play sets regularly and you can rally from the baseline, but points feel random and the net is scary.',
    goals: [
      'Volley on both sides with a continental grip',
      'Hit a slice backhand for defence and approach',
      'Recognise the five game situations and act accordingly',
      'Use a between-point routine',
    ],
    items: [
      { label: 'Learn the forehand volley', to: '/studio/forehand-volley' },
      { label: 'Learn the backhand volley', to: '/studio/backhand-volley' },
      { label: 'Study the slice', to: '/studio/slice' },
      { label: 'Read the five game situations', to: '/learn/tactics' },
      { label: 'Learn the between-point routine', to: '/learn/mental' },
      { label: 'Do the approach and split drill', to: '/learn/footwork' },
      { label: 'Practise the crossover step for wide balls', to: '/studio/crossover' },
    ],
    milestone: '50-ball cooperative rally from the baseline, and win a volley-to-baseline drill by getting 10 volleys in a row into the court.',
  },
  {
    n: 4,
    title: 'Solid all round',
    range: '120–200 hours',
    who: 'You have every basic stroke and a reliable rally ball. You want to stop losing to players who just push.',
    goals: [
      'Hit a reliable second serve with spin',
      'Play the overhead with confidence',
      'Return first and second serves with different intentions',
      'Understand stances and hit off the outside leg',
    ],
    items: [
      { label: 'Study the smash and the drop step footwork', to: '/studio/smash' },
      { label: 'Learn to read and return serves', to: '/studio/return' },
      { label: 'Read stances explained', to: '/learn/footwork' },
      { label: 'Run the spider drill and log your time', to: '/learn/footwork' },
      { label: 'Read strength for tennis and start twice-weekly sessions', to: '/learn/fitness' },
      { label: 'Read patterns of play: serve plus one', to: '/learn/tactics' },
    ],
    milestone: 'Serve 7 of 10 second serves in with spin, 5 of 10 overheads into the court from a fed lob, and win a practice set against a pusher.',
  },
  {
    n: 5,
    title: 'Competitor',
    range: '200–350 hours',
    who: 'You play club matches or box leagues and you win about as often as you lose. You want to be a match player rather than a hitter.',
    goals: [
      'Play at least two patterns of play on purpose',
      'Change direction only on the right ball',
      'Handle nerves on big points with a plan',
      'Play doubles with proper positioning',
    ],
    items: [
      { label: 'Read patterns of play and pick two to own', to: '/learn/tactics' },
      { label: 'Read handling nerves and chokes', to: '/learn/mental' },
      { label: 'Read doubles tactics basics', to: '/learn/tactics' },
      { label: 'Do serve plus one recovery and cone triangle hitting', to: '/learn/footwork' },
      { label: 'Start tennis-specific interval runs', to: '/learn/fitness' },
      { label: 'Learn the drop shot as a change of pace', to: '/studio/drop-shot' },
      { label: 'Keep a training journal: practice with purpose', to: '/learn/mental' },
    ],
    milestone: 'Win a set in a competitive match using the serve plus one pattern at least five times, and hit 8 of 10 cross-court balls past the service line under rally pressure.',
  },
  {
    n: 6,
    title: 'Weapon builder',
    range: '350–500 hours',
    who: 'You compete regularly and hold your own. Now you need a shot that wins points, not just a game that avoids losing them.',
    goals: [
      'Develop one weapon: a serve, forehand or return that opponents fear',
      'Use the inside-out forehand pattern',
      'Attack short balls with a swing volley or approach',
      'Read the opponent’s racquet for early anticipation',
    ],
    items: [
      { label: 'Study the swing volley', to: '/studio/swing-volley' },
      { label: 'Refine the serve: spin, placement, disguise', to: '/studio/serve' },
      { label: 'Compare your forehand with the pros', to: '/pros' },
      { label: 'Medicine ball throws and lateral lunge series', to: '/learn/fitness' },
      { label: 'Read recovery and court positioning', to: '/learn/footwork' },
      { label: 'Read how to learn a stroke and film yourself', to: '/learn/mental' },
    ],
    milestone: 'Serve 6 of 10 first serves into a chosen half of the box on call, and win 60 % of practice points that start with a short ball you attack.',
  },
  {
    n: 7,
    title: 'Tactician',
    range: '500–750 hours',
    who: 'You have a weapon and a game plan. You want to beat players who are technically as good as you.',
    goals: [
      'Adapt tactics to opponent, surface and conditions',
      'Vary spin, height and pace on purpose',
      'Defend from behind the baseline and reset the point',
      'Play the net in singles when the approach is right',
    ],
    items: [
      { label: 'Study the back smash for lobs over your head', to: '/studio/back-smash' },
      { label: 'Refresh the slice for defence and approach', to: '/studio/slice' },
      { label: 'Learn how surfaces change the game', to: '/learn/courts' },
      { label: 'Read endurance and speed and build a weekly plan', to: '/learn/fitness' },
      { label: 'Read moving forward and back', to: '/learn/footwork' },
      { label: 'Study how the pros build points', to: '/pros' },
    ],
    milestone: 'Win a match by changing the game plan mid-match and record in your journal what you changed and why. Spider drill under 18 seconds.',
  },
  {
    n: 8,
    title: 'Tournament tough',
    range: '750–1,000 hours',
    who: 'You play sanctioned tournaments or high-level league. You lose mostly to nerves, fatigue or one weakness that gets found.',
    goals: [
      'Play three-set matches at consistent intensity',
      'Hold serve under pressure with a reliable second serve',
      'Eliminate the one shot opponents target',
      'Run a full between-point and changeover routine automatically',
    ],
    items: [
      { label: 'Audit every stroke against the models', to: '/studio/backhand-two-handed' },
      { label: 'Return practice: block, chip and drive', to: '/studio/return' },
      { label: 'Shoulder care band work as a daily routine', to: '/learn/fitness' },
      { label: 'Mental training: routines and pressure practice', to: '/learn/mental' },
      { label: 'Know the rules for tournament play and officiating', to: '/learn/rules' },
      { label: 'Check racquet, string and tension choices', to: '/learn/racquets' },
    ],
    milestone: 'Serve 7 of 10 second serves to the backhand corner target under a 30-30 scenario, and complete a three-set practice match with your first-serve percentage above 60 % in every set.',
  },
  {
    n: 9,
    title: 'All-court player',
    range: '1,000–1,500 hours',
    who: 'You win tournament matches and you are comfortable everywhere on the court. You want the finishing touches.',
    goals: [
      'Finish points at the net from any approach',
      'Play drop shots and lobs as real tactical options',
      'Use the tweener or back smash when a lob truly beats you',
      'Coach yourself: diagnose and fix your own game between lessons',
    ],
    items: [
      { label: 'Refine the drop shot and disguise it', to: '/studio/drop-shot' },
      { label: 'Study the tweener for the desperate lob', to: '/studio/tweener' },
      { label: 'Study the back smash', to: '/studio/back-smash' },
      { label: 'Compare your movement patterns with the pros', to: '/pros' },
      { label: 'Refresh doubles tactics for team events', to: '/learn/tactics' },
      { label: 'Full strength and conditioning programme', to: '/learn/fitness' },
    ],
    milestone: 'Win a practice set in which every point you win comes from a net approach, and win a tournament match in which you use at least three different patterns of play.',
  },
  {
    n: 10,
    title: 'Complete player',
    range: '1,500+ hours',
    who: 'You are a tournament-level all-court player. Improvement now comes from detail, periodisation and staying healthy.',
    goals: [
      'Periodise the season: build, compete, recover',
      'Maintain every stroke with regular video review',
      'Stay injury-free with a structured prevention routine',
      'Give back: help a lower-level player through the path',
    ],
    items: [
      { label: 'Frame-by-frame review of the serve against the pros', to: '/studio/serve' },
      { label: 'Pro comparison across every stroke', to: '/pros' },
      { label: 'Plan the season with strength, speed and recovery blocks', to: '/learn/fitness' },
      { label: 'Refine the mental game for long tournaments', to: '/learn/mental' },
      { label: 'Keep footwork sharp with timed spider drills', to: '/learn/footwork' },
      { label: 'Stay current on rules and equipment regulations', to: '/learn/rules' },
    ],
    milestone: 'Complete a tournament season with a written plan, a match journal for every match, and no time lost to preventable injury. Spider drill under 16 seconds.',
  },
]
