import type { JuniorSize, RacquetSpec } from './types'

export const RACQUET_TYPES: RacquetSpec[] = [
  {
    id: 'power-oversize',
    name: 'Power / oversize',
    headSize: '105–118 sq in (677–761 cm²)',
    weight: '230–275 g unstrung, often 27.5 in (69.9 cm) long',
    balance: 'Head-heavy, 2–6 pts HH (35–37 cm from the butt)',
    stiffness: 'Stiff, RA 68–75, wide 26–30 mm beam',
    stringPattern: '16x19 or open 16x18',
    forWhom: 'Beginners with short, slow swings, seniors, and players who want free depth without effort. Head Ti.S6 (115 sq in, 225 g), Wilson Clash 108, Babolat Boost Drive and Prince Ripstick 105 are typical.',
    feel: 'Trampoline-like. The huge sweet spot forgives off-centre hits and the light frame is easy to swing, but the stiff, head-heavy set-up transmits shock to the arm, and once your swing gets faster the ball starts flying long.',
  },
  {
    id: 'tweener-all-round',
    name: 'Tweener / all-round',
    headSize: '98–102 sq in, almost always 100 sq in (645 cm²)',
    weight: '280–305 g unstrung, 27 in (68.6 cm) long',
    balance: 'Slightly head-light, 4–7 pts HL (32–33 cm)',
    stiffness: 'Medium-stiff, RA 63–72, 22–26 mm beam',
    stringPattern: '16x19',
    forWhom: 'The biggest category by far, for improving beginners through to advanced club players. Babolat Pure Drive and Pure Aero, Wilson Blade 100, Head Speed MP, Yonex EZONE 100 and Tecnifibre TF-X1 are all tweeners.',
    feel: 'Balanced between power and control with easy spin from the open pattern. Enough mass to be stable against pace, light enough to swing fast. If you do not know what you want, start here.',
  },
  {
    id: 'modern-players',
    name: 'Modern player’s racquet',
    headSize: '97–100 sq in (626–645 cm²)',
    weight: '300–315 g unstrung',
    balance: 'Head-light, 6–9 pts HL (31–32.5 cm), swingweight 320–335',
    stiffness: 'Medium, RA 60–68, 21–23 mm beam',
    stringPattern: '16x19 (some 18x20 versions)',
    forWhom: 'Advanced juniors and adults with full, fast swings who generate their own power and want feel and control at high racquet-head speed. Wilson Blade 98, Head Gravity MP and Pro, Babolat Pure Strike 98 and Yonex VCORE 98 are examples.',
    feel: 'Plush and connected. The flexible, thinner beam gives you feedback on every hit, and the extra mass plows through heavy balls. You must bring the swing speed; a short swing produces a short ball.',
  },
  {
    id: 'classic-control',
    name: 'Classic control racquet',
    headSize: '93–98 sq in (600–632 cm²)',
    weight: '310–340 g unstrung',
    balance: 'Very head-light, 8–12 pts HL (30.5–32 cm), swingweight 325–345',
    stiffness: 'Flexible, RA 58–65, 17–21 mm beam',
    stringPattern: '18x20 or dense 16x19',
    forWhom: 'Experienced players with long, technically sound strokes who value precision and flat hitting over spin and free power. Wilson Pro Staff 97 and RF 97, Head Prestige Pro and Prince Phantom 93P belong here, as did the 85 sq in Pro Staff 6.0 of the Sampras era.',
    feel: 'Precise and solid but unforgiving. The small head and dense pattern let you swing at full speed and aim at lines, but off-centre hits lose power quickly and the heavy frame is tiring over three sets if your fitness is not there.',
  },
  {
    id: 'junior-aluminium',
    name: 'Junior aluminium',
    headSize: '80–100 sq in (516–645 cm²)',
    weight: '170–240 g strung depending on length',
    balance: 'Roughly even balance for a child’s hand',
    stiffness: 'Aluminium frame, no RA rating; graphite composite junior frames start around 25 in',
    stringPattern: '16x17 to 16x19, pre-strung',
    forWhom: 'Children from age 4 to about 10 in lengths of 19, 21, 23 and 25 in, matched to the red and orange ball stages. Babolat Ballfighter, Head Speed Jr, Wilson US Open Jr and Yonex EZONE Jr are typical, and cost 20–40 euros.',
    feel: 'Light, lively and tough enough to survive being dropped. The aluminium and factory strings feel a little dead, which does not matter at this stage. Move to a graphite 25 or 26 in frame when the child reaches the green ball and starts producing their own spin.',
  },
]

export const JUNIOR_SIZES: JuniorSize[] = [
  { length: '19 in (48 cm)', ageRange: '4 years and under', heightRange: 'up to 100 cm (3 ft 3 in)', ballStage: 'Red (stage 3), foam then felt' },
  { length: '21 in (53 cm)', ageRange: '4–5 years', heightRange: '100–115 cm (3 ft 3 in – 3 ft 9 in)', ballStage: 'Red (stage 3)' },
  { length: '23 in (58 cm)', ageRange: '6–8 years', heightRange: '115–125 cm (3 ft 9 in – 4 ft 1 in)', ballStage: 'Red moving to orange (stage 2)' },
  { length: '25 in (63.5 cm)', ageRange: '9–10 years', heightRange: '125–140 cm (4 ft 1 in – 4 ft 7 in)', ballStage: 'Orange (stage 2) moving to green' },
  { length: '26 in (66 cm)', ageRange: '10–11 years', heightRange: '140–150 cm (4 ft 7 in – 4 ft 11 in)', ballStage: 'Green (stage 1)' },
  { length: '27 in (68.6 cm), adult', ageRange: '11–12 years and up', heightRange: '150 cm (4 ft 11 in) and taller', ballStage: 'Green then standard yellow' },
]

export const STRING_TYPES: { id: string; name: string; feel: string; durability: string; forWhom: string; tension: string }[] = [
  {
    id: 'natural-gut',
    name: 'Natural gut',
    feel: 'The benchmark. Made from twisted strands of cow intestine serosa, it is the most elastic string there is: soft, powerful, lively and unusually good at holding tension. Babolat VS Touch and Wilson Natural Gut are the references.',
    durability: 'Moderate for a soft string, but it hates moisture and frays quickly with heavy spin. Expensive: 40–55 euros a set.',
    forWhom: 'Players with arm problems, players who want maximum feel, and as the mains in a pro-style hybrid with a polyester cross.',
    tension: '23–27 kg (50–60 lb). It stays close to that tension for weeks.',
  },
  {
    id: 'multifilament',
    name: 'Multifilament',
    feel: 'Hundreds or thousands of thin nylon microfibres bundled together to mimic gut. Soft, comfortable and powerful with good shock absorption. Tecnifibre X-One Biphase, Wilson NXT and Head Velocity MLT are the usual picks.',
    durability: 'Low to moderate; the outer fibres fray and the string snaps once enough are cut. Loses tension steadily over 4–8 weeks.',
    forWhom: 'Beginners and club players who want comfort, anyone with tennis elbow, and flatter hitters who do not break strings often.',
    tension: '23–26 kg (50–57 lb). Do not go too low or the ball flies.',
  },
  {
    id: 'synthetic-gut',
    name: 'Synthetic gut',
    feel: 'A solid nylon core with one or more outer wraps. Crisp, medium-firm and unremarkable, which is a compliment: it does everything adequately. Prince Synthetic Gut Duraflex and Gosen OG Sheep Micro are classics and cost 4–8 euros a set.',
    durability: 'Decent for a nylon string and the cheapest option by far, so most factory-strung racquets come with it.',
    forWhom: 'Beginners, budget-conscious players, and juniors who go through a lot of strings. A fine choice until you know what you are missing.',
    tension: '23–26 kg (50–57 lb).',
  },
  {
    id: 'polyester',
    name: 'Polyester (poly)',
    feel: 'A single stiff monofilament of polyester or co-polyester. Low-powered, very controlled, and the strings snap back into place at contact, which is where modern heavy topspin comes from. Luxilon ALU Power, Babolat RPM Blast and Solinco Hyper-G dominate the tour.',
    durability: 'Extremely hard to break, but poly loses tension fast and turns dead and boardy long before it snaps, usually within 10–20 hours of hitting. Cut it out rather than waiting for it to break.',
    forWhom: 'Advanced players and strong juniors who swing fast, hit heavy spin and break softer strings quickly. Not for beginners, not for anyone with arm pain, and not recommended under about 13 years old.',
    tension: '20–25 kg (44–55 lb), typically 2–4 kg lower than you would string a nylon.',
  },
  {
    id: 'hybrid',
    name: 'Hybrid',
    feel: 'Two different strings: one in the mains (vertical) and another in the crosses. Gut or multifilament mains with a poly cross gives comfort and power with added spin and durability; poly mains with a softer cross gives the poly’s control with a bit more comfort. Federer used natural gut mains with Luxilon ALU Power Rough crosses.',
    durability: 'Better than the soft string alone because the poly protects it in one direction. The two strings lose tension at different rates, so restring when either feels off.',
    forWhom: 'Intermediate and advanced players who want a compromise, and string breakers who find full poly too harsh.',
    tension: 'String the poly 1–2 kg lower than the softer string, for example 24 kg gut mains and 22 kg poly crosses.',
  },
]
