import type { Surface } from './types'

export const SURFACES: Surface[] = [
  {
    id: 'hard',
    name: 'Hard court',
    speed: 3,
    bounce: 3,
    typicalRally: 'Medium rallies of 4–8 shots. The bounce is even and predictable, so baseline exchanges are fast and true, and a big serve plus one strong groundstroke wins a lot of points.',
    famousFor: 'The Australian Open (GreenSet since 2020, Plexicushion before that) and the US Open (Laykold since 2020, DecoTurf before that). Most public courts in North America, Asia and Australia are hard courts.',
    construction: 'Asphalt or concrete base, then several coats of acrylic resin. The colour coat is mixed with silica sand: more sand and coarser grains slow the court down, less sand speeds it up. Cushioned systems such as Laykold Masters or Plexicushion add rubber layers under the acrylic to soften impact. The ITF Court Pace Rating for tour hard courts usually sits in category 3 (medium, 35–39) or 4 (medium-fast, 40–44).',
    playingStyle: 'The all-round surface. Serve and first-strike tennis works because the bounce is reliable and slightly skidding. Flat hitters and big servers gain; heavy topspin still kicks but not as much as on clay. Points end quicker than on clay, so take the initiative rather than waiting for errors.',
    footwear: 'All-court shoes with a durable herringbone or modified outsole and lateral support. Hard courts chew soles, so look for a six-month outsole guarantee. A firmer midsole protects the foot from the unforgiving surface.',
    bodyNote: 'The hardest surface on the body. Stopping is abrupt and there is no give, so knees, shins and lower back take repeated load. Warm up properly, limit consecutive long sessions when starting out, and treat cushioned acrylic courts as a bonus.',
  },
  {
    id: 'clay',
    name: 'Clay court',
    speed: 1,
    bounce: 5,
    typicalRally: 'Long rallies of 8–15 shots and more. The loose top layer grips the ball, kills pace and lifts the bounce, so winners are hard to hit and consistency plus point construction matter most.',
    famousFor: 'Roland Garros (red clay), the Monte Carlo, Rome and Madrid Masters, and Har-Tru green clay across the US. Most club courts in Spain, Italy, France, Argentina and Germany are clay.',
    construction: 'Roland Garros courts are five layers roughly 80 cm deep: large stones, then about 30 cm of gravel, then roughly 7–8 cm of clinker (coal residue that holds moisture), then 6–7 cm of finely crushed white limestone, and finally just 1–2 mm of crushed red brick dusted on top. The brick is what you see and slide on; the limestone underneath is the real playing surface. Green clay (Har-Tru) uses crushed metabasalt, drains faster and plays slightly quicker. Courts are watered and rolled daily.',
    playingStyle: 'Patience, heavy topspin and depth. Higher bounces reward players who hit above shoulder height comfortably, so semi-western and western grips shine. Drop shots are effective because opponents sit deep. Learn to slide into the ball and recover instead of stopping and restarting. Serve-and-volley is rare; flat serves lose their sting.',
    footwear: 'Clay-specific shoes with a full herringbone (zigzag) outsole that grips when planted and releases when you slide, plus a tighter upper mesh that keeps the clay out. A smooth-soled shoe on clay is dangerous.',
    bodyNote: 'The kindest surface for joints because the top layer gives on every step. Longer rallies test aerobic fitness and legs, and sliding puts new demands on hips and adductors, so add hip mobility work. Expect red dust on socks, shoes and the ball.',
  },
  {
    id: 'grass',
    name: 'Grass court',
    speed: 5,
    bounce: 1,
    typicalRally: 'Short rallies of 2–5 shots. The ball skids through low and quick, especially in the first week when the turf is lush, so the serve, return and first volley decide most points.',
    famousFor: 'Wimbledon and the short grass swing that leads into it (Queen’s Club, Halle, Eastbourne, Stuttgart, Berlin, ’s-Hertogenbosch). Grass courts are rare outside Britain, Germany, the Netherlands and Australia because they are costly to maintain.',
    construction: 'Wimbledon courts are 100% perennial ryegrass since 2001 (it replaced a 70/30 ryegrass and creeping red fescue mix for durability) and are mown to exactly 8 mm every day of the Championships. The grass grows on a firm, compacted clay loam base rolled to a hardness comparable to a hard court; the firmness of the soil, not the grass, sets the speed. Courts are relaid with seed each autumn, and by the second week of the tournament the baseline area is worn brown and plays higher and slower.',
    playingStyle: 'Attack. Serve big and follow it in, chip and charge on returns, and keep your slice low because the ball stays low anyway. Bend your knees more than anywhere else: a lot of contact points are below knee height. Footing is less secure, so shorten steps and stay low rather than sprinting flat out. Topspin bounces are softened, so flat and slice players gain.',
    footwear: 'Grass shoes have dimpled or pimpled rubber outsoles for grip on the turf. Most clubs ban anything else because herringbone tears the surface. Some tournaments allow all-court shoes when the grass is dry.',
    bodyNote: 'Soft underfoot and easy on joints, but slipping is the main risk, particularly behind the baseline on a damp morning. Low bounces load the quads and lower back through constant deep knee bends. Move in small steps and never plant a foot flat while turning.',
  },
  {
    id: 'indoor',
    name: 'Indoor court',
    speed: 4,
    bounce: 2,
    typicalRally: 'Medium-short rallies of 3–7 shots. No wind, no sun and controlled lighting make the ball fly true, so serving and aggressive baseline play thrive and error rates drop.',
    famousFor: 'The ATP Finals (Turin), the Paris Masters, Rotterdam, Vienna and Basel, plus the Davis Cup Finals. Most of the tour’s autumn events are indoor hard courts. Carpet (Supreme, Taraflex) was common indoors until the ATP dropped it from the tour in 2009; a few clubs still have it.',
    construction: 'Usually an acrylic hard court laid over concrete or a raised wooden floor (GreenSet, Rebound Ace, Laykold). Carpet courts are rolls of textured synthetic surface laid over a firm base, and they play fast and low. Some clubs use artificial clay (a sand-filled synthetic turf) indoors, which is slower and softer. Indoor air is still and slightly drier, so the ball travels a little faster than the same court outdoors.',
    playingStyle: 'Take advantage of perfect conditions: aim closer to the lines, flatten the serve, and serve-and-volley more than outdoors. Without wind you can trust your toss. Ceiling height matters for the lob and smash; check lights before you flick a high ball. Sound is louder, so use the acoustic feedback to judge how cleanly you are striking.',
    footwear: 'All-court hard-court shoes with non-marking soles (required in nearly every hall). For carpet, use a smooth or lightly textured outsole; herringbone grips too much and can twist an ankle. Wipe soles before stepping on so dust does not make the court slick.',
    bodyNote: 'Indoor hard courts share the hard-court impact issue, and carpet adds a sticky grip that increases ankle and knee twisting risk. Warm indoor air dehydrates you faster than you expect because sweat evaporates quickly, so drink at every changeover.',
  },
]
